-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				rawText="Summon an Azmerian Swarm when you kill a target affected by an [ElementalAilments|Elemental Ailment]",
				text="Summon an Azmerian Swarm when you kill a target affected by an Elemental Ailment"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% chance to summon an Azmerian Swarm when you kill a target affected by an [ElementalAilments|Elemental Ailment]",
				text="{0}% chance to summon an Azmerian Swarm when you kill a target affected by an Elemental Ailment"
			}
		},
		stats={
			[1]="skill_grants_%_chance_to_summon_azmerian_swarm_on_kill_affected_by_elemental_ailment"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% chance to summon an Azmerian Swarm when you [HitDamage|Hit] a Rare or Unique target affected by an [ElementalAilments|Elemental Ailment]",
				text="{0}% chance to summon an Azmerian Swarm when you Hit a Rare or Unique target affected by an Elemental Ailment"
			}
		},
		stats={
			[1]="skill_grants_%_chance_to_summon_azmerian_swarm_on_hitting_unique_or_rare_enemy_affected_by_elemental_ailment"
		}
	},
	[3]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=0,
						[2]="#"
					}
				},
				rawText="Maximum {0:+d} Azmerian Swarms",
				text="Maximum {0:+d} Azmerian Swarms"
			},
			[2]={
				limit={
					[1]={
						[1]=0,
						[2]="#"
					}
				},
				rawText="Maximum {0} Azmerian Swarms",
				text="Maximum {0} Azmerian Swarms"
			}
		},
		stats={
			[1]="max_azmerian_swarms"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Swarms have {0}% chance to inflict 1 [FaerieFire|Faerie Fire] on [HitDamage|Hit]",
				text="Swarms have {0}% chance to inflict 1 Faerie Fire on Hit"
			}
		},
		stats={
			[1]="%_chance_to_apply_hounded_by_wisps_on_hit"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Swarms [Conversion|Convert] {0}% of [Physical] Damage to a random [ElementalDamage|Element]",
				text="Swarms Convert {0}% of Physical Damage to a random Element"
			}
		},
		stats={
			[1]="non_skill_base_physical_damage_%_to_convert_to_random_element"
		}
	},
	[6]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Swarm duration is {0} second",
				text="Swarm duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Swarm duration is {0} seconds",
				text="Swarm duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[7]={
		[1]={
		},
		stats={
			[1]="minion_duration"
		}
	},
	[8]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Swarms have 1% increased [Attack] Speed\nper {0} of your [Dexterity]",
				text="Swarms have 1% increased Attack Speed\nper {0} of your Dexterity"
			}
		},
		stats={
			[1]="active_skill_minion_1%_attack_speed_+%_per_X_player_dexterity"
		}
	},
	[9]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Swarms deal {0}% more Damage with [HitDamage|Hits] for each type of [ElementalAilments|Elemental Ailment] on target",
				text="Swarms deal {0}% more Damage with Hits for each type of Elemental Ailment on target"
			}
		},
		stats={
			[1]="minion_damage_+%_final_per_different_elemental_ailment_on_target"
		}
	},
	["%_chance_to_apply_hounded_by_wisps_on_hit"]=4,
	["active_skill_minion_1%_attack_speed_+%_per_X_player_dexterity"]=8,
	["base_skill_effect_duration"]=6,
	["max_azmerian_swarms"]=3,
	["minion_damage_+%_final_per_different_elemental_ailment_on_target"]=9,
	["minion_duration"]=7,
	["non_skill_base_physical_damage_%_to_convert_to_random_element"]=5,
	parent="skill_stat_descriptions",
	["skill_grants_%_chance_to_summon_azmerian_swarm_on_hitting_unique_or_rare_enemy_affected_by_elemental_ailment"]=2,
	["skill_grants_%_chance_to_summon_azmerian_swarm_on_kill_affected_by_elemental_ailment"]=1
}