-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0} second duration between [Corpse] consumptions",
				text="{0} second duration between Corpse consumptions"
			}
		},
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="{0:+d} maximum Corpse Beetle",
				text="{0:+d} maximum Corpse Beetle"
			},
			[2]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="{0:+d} maximum Corpse Beetles",
				text="{0:+d} maximum Corpse Beetles"
			},
			[3]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Maximum {0} Corpse Beetle",
				text="Maximum {0} Corpse Beetle"
			},
			[4]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Maximum {0} Corpse Beetles",
				text="Maximum {0} Corpse Beetles"
			}
		},
		stats={
			[1]="maximum_corpse_beetles_allowed"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="secondary_skill_effect_duration"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Summons {0} Beetle per [Corpse] consumed",
				text="Summons {0} Beetle per Corpse consumed"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Summons {0} Beetles per [Corpse] consumed",
				text="Summons {0} Beetles per Corpse consumed"
			}
		},
		stats={
			[1]="skill_specific_stat_description_mode"
		}
	},
	["base_secondary_skill_effect_duration"]=1,
	["maximum_corpse_beetles_allowed"]=2,
	parent="skill_stat_descriptions",
	["secondary_skill_effect_duration"]=3,
	["skill_specific_stat_description_mode"]=4
}