-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Buff] duration is {0} second",
				text="Buff duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Buff] duration is {0} seconds",
				text="Buff duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Buff] grants {0}% Increased [ESRecharge|Energy Shield Recharge Rate]",
				text="Buff grants {0}% Increased Energy Shield Recharge Rate"
			}
		},
		stats={
			[1]="djinn_granted_energy_shield_recharge_rate_+%"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["base_skill_effect_duration"]=1,
	["djinn_granted_energy_shield_recharge_rate_+%"]=2,
	parent="skill_stat_descriptions",
	["skill_effect_duration"]=3
}