-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Chain|Chains] {0} time",
				text="Chains {0} time"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Chain|Chains] {0} times",
				text="Chains {0} times"
			}
		},
		stats={
			[1]="number_of_chains"
		}
	},
	["number_of_chains"]=1,
	parent="skill_stat_descriptions"
}