-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="{0:+d} metre to impact radius",
				text="{0:+d} metre to impact radius"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="{0:+d} metres to impact radius",
				text="{0:+d} metres to impact radius"
			},
			[3]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Impact radius is {0} metre",
				text="Impact radius is {0} metre"
			},
			[4]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Impact radius is {0} metres",
				text="Impact radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius",
			[2]="quality_display_active_skill_base_area_of_effect_radius_is_gem"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				rawText="Storm radius is {0} metre",
				text="Storm radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Storm radius is {0} metres",
				text="Storm radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_secondary_area_of_effect_radius"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="active_skill_secondary_area_of_effect_radius"
		}
	},
	[5]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Storm duration is {0} second",
				text="Storm duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Storm duration is {0} seconds",
				text="Storm duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[6]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="One impact every {0} seconds",
				text="One impact every {0} seconds"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{1} Bolts",
				text="{1} Bolts"
			}
		},
		stats={
			[1]="fire_storm_fireball_delay_ms",
			[2]="vaal_firestorm_number_of_meteors"
		}
	},
	[7]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0}% increased bolt frequency",
				text="Fire Infusion grants {0}% increased bolt frequency"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0}% reduced bolt frequency",
				text="Fire Infusion grants {0}% reduced bolt frequency"
			}
		},
		stats={
			[1]="firestorm_bolt_frequency_+%_if_consumed_fire_infusion"
		}
	},
	[8]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0}% increased Damage",
				text="Fire Infusion grants {0}% increased Damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0}% reduced Damage",
				text="Fire Infusion grants {0}% reduced Damage"
			}
		},
		stats={
			[1]="firestorm_damage_+%_if_consumed_fire_infusion"
		}
	},
	[9]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0:+d} metre to storm radius",
				text="Fire Infusion grants {0:+d} metre to storm radius"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[ElementalInfusion|Fire Infusion] grants {0:+d} metres to storm radius",
				text="Fire Infusion grants {0:+d} metres to storm radius"
			}
		},
		stats={
			[1]="firestorm_secondary_radius_+_if_consumed_fire_infusion"
		}
	},
	[10]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	[11]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Firestorm Limit@{0}",
				text="Firestorm Limit@{0}"
			}
		},
		stats={
			[1]="virtual_firestorm_max_number_of_storms"
		}
	},
	[12]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Limit] {0} Firestorm",
				text="Limit {0} Firestorm"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Limit] {0} Firestorms",
				text="Limit {0} Firestorms"
			}
		},
		stats={
			[1]="firestorm_max_number_of_storms"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	["active_skill_base_secondary_area_of_effect_radius"]=3,
	["active_skill_secondary_area_of_effect_radius"]=4,
	["base_skill_effect_duration"]=5,
	["fire_storm_fireball_delay_ms"]=6,
	["firestorm_bolt_frequency_+%_if_consumed_fire_infusion"]=7,
	["firestorm_damage_+%_if_consumed_fire_infusion"]=8,
	["firestorm_max_number_of_storms"]=12,
	["firestorm_secondary_radius_+_if_consumed_fire_infusion"]=9,
	parent="skill_stat_descriptions",
	["quality_display_active_skill_base_area_of_effect_radius_is_gem"]=2,
	["skill_effect_duration"]=10,
	["vaal_firestorm_number_of_meteors"]=6,
	["virtual_firestorm_max_number_of_storms"]=11
}