-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Wall deals {0} [Fire] Damage per second",
				text="Wall deals {0} Fire Damage per second"
			}
		},
		stats={
			[1]="base_fire_damage_to_deal_per_minute"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Lingering [Ignite] duration is {0} second",
				text="Lingering Ignite duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Lingering [Ignite] duration is {0} seconds",
				text="Lingering Ignite duration is {0} seconds"
			}
		},
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Wall duration is {0} second",
				text="Wall duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Wall duration is {0} seconds",
				text="Wall duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Projectile|Projectiles] which pass through the wall deal {0} to {1} Added [Fire] Damage",
				text="Projectiles which pass through the wall deal {0} to {1} Added Fire Damage"
			}
		},
		stats={
			[1]="flame_wall_minimum_added_fire_damage",
			[2]="flame_wall_maximum_added_fire_damage"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Projectile|Projectiles] which pass through the [ElementalInfusion|Infused] wall deal {0} to {1} Added [Lightning] Damage",
				text="Projectiles which pass through the Infused wall deal {0} to {1} Added Lightning Damage"
			}
		},
		stats={
			[1]="flame_wall_minimum_added_lightning_damage_to_add_to_projectile",
			[2]="flame_wall_maximum_added_lightning_damage_to_add_to_projectile"
		}
	},
	[6]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Projectile|Projectiles] which pass through the wall gain extra {0}% damage as [Fire]",
				text="Projectiles which pass through the wall gain extra {0}% damage as Fire"
			}
		},
		stats={
			[1]="flame_wall_projectiles_gain_all_damage_%_as_fire"
		}
	},
	[7]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Lingering [Ignite] deals {0} [Fire] Damage per second",
				text="Lingering Ignite deals {0} Fire Damage per second"
			}
		},
		stats={
			[1]="secondary_base_fire_damage_to_deal_per_minute"
		}
	},
	[8]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Lingering [Ignite] damage per second@{0}",
				text="Lingering Ignite damage per second@{0}"
			}
		},
		stats={
			[1]="secondary_intermediary_fire_skill_dot_damage_to_deal_per_minute"
		}
	},
	[9]={
		[1]={
		},
		stats={
			[1]="secondary_skill_effect_duration"
		}
	},
	[10]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	[11]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Ignite|Ignites] as though dealing {0} to {1} [Fire] damage",
				text="Ignites as though dealing {0} to {1} Fire damage"
			}
		},
		stats={
			[1]="spell_minimum_base_fire_damage",
			[2]="spell_maximum_base_fire_damage"
		}
	},
	[12]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="+{0} metres to Wall length",
				text="+{0} metres to Wall length"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Wall length is {0} metres",
				text="Wall length is {0} metres"
			}
		},
		stats={
			[1]="wall_maximum_length"
		}
	},
	["base_fire_damage_to_deal_per_minute"]=1,
	["base_secondary_skill_effect_duration"]=2,
	["base_skill_effect_duration"]=3,
	["flame_wall_maximum_added_fire_damage"]=4,
	["flame_wall_maximum_added_lightning_damage_to_add_to_projectile"]=5,
	["flame_wall_minimum_added_fire_damage"]=4,
	["flame_wall_minimum_added_lightning_damage_to_add_to_projectile"]=5,
	["flame_wall_projectiles_gain_all_damage_%_as_fire"]=6,
	parent="skill_stat_descriptions",
	["secondary_base_fire_damage_to_deal_per_minute"]=7,
	["secondary_intermediary_fire_skill_dot_damage_to_deal_per_minute"]=8,
	["secondary_skill_effect_duration"]=9,
	["skill_effect_duration"]=10,
	["spell_maximum_base_fire_damage"]=11,
	["spell_minimum_base_fire_damage"]=11,
	["wall_maximum_length"]=12
}