-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Fissure duration is {0} second",
				text="Fissure duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Fissure duration is {0} seconds",
				text="Fissure duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Limit] {0} Fissure",
				text="Limit {0} Fissure"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Limit] {0} Fissures",
				text="Limit {0} Fissures"
			}
		},
		stats={
			[1]="forge_hammer_base_maximum_number_of_fissures"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="forge_hammer_maximum_number_of_fissures"
		}
	},
	[4]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["base_skill_effect_duration"]=1,
	["forge_hammer_base_maximum_number_of_fissures"]=2,
	["forge_hammer_maximum_number_of_fissures"]=3,
	parent="skill_stat_descriptions",
	["skill_effect_duration"]=4
}