-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="While the [Buff] is active, automatically [Block] from all directions and inflict [ParriedDebuff|Parried] to [Block|Blocked] enemies",
				text="While the Buff is active, automatically Block from all directions and inflict Parried to Blocked enemies"
			}
		},
		stats={
			[1]="display_statset_no_hit_damage"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Buff] duration is {0} second",
				text="Buff duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Buff] duration is {0} seconds",
				text="Buff duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[3]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0:+d}% more [StunThreshold|Stun Threshold] while [Buff] is active",
				text="{0:+d}% more Stun Threshold while Buff is active"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more [StunThreshold|Stun Threshold] while [Buff] is active",
				text="{0}% more Stun Threshold while Buff is active"
			},
			[3]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less [StunThreshold|Stun Threshold] while [Buff] is active",
				text="{0}% less Stun Threshold while Buff is active"
			}
		},
		stats={
			[1]="runic_fortress_stun_threshold_+%_final"
		}
	},
	[4]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0:+d}% more [StunThreshold|Stun Threshold] while [Buff] is active per 10 [Ward|Runic Ward] spent",
				text="{0:+d}% more Stun Threshold while Buff is active per 10 Runic Ward spent"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more [StunThreshold|Stun Threshold] while [Buff] is active per 10 [Ward|Runic Ward] spent",
				text="{0}% more Stun Threshold while Buff is active per 10 Runic Ward spent"
			},
			[3]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less [StunThreshold|Stun Threshold] while [Buff] is active per 10 [Ward|Runic Ward] spent",
				text="{0}% less Stun Threshold while Buff is active per 10 Runic Ward spent"
			}
		},
		stats={
			[1]="runic_fortress_stun_threshold_+%_final_per_10_ward_spent"
		}
	},
	[5]={
		[1]={
		},
		stats={
			[1]="secondary_skill_effect_duration"
		}
	},
	[6]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[ParriedDebuff|Parried Debuff] makes targets take {0}% more [Attack] Damage",
				text="Parried Debuff makes targets take {0}% more Attack Damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[ParriedDebuff|Parried Debuff] makes targets take {0}% less [Attack] Damage",
				text="Parried Debuff makes targets take {0}% less Attack Damage"
			}
		},
		stats={
			[1]="base_parry_buff_damage_taken_+%_final_to_apply"
		}
	},
	[7]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[ParriedDebuff|Parried] [Debuff] lasts for an additional {0:+d} seconds",
				text="Parried Debuff lasts for an additional {0:+d} seconds"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[ParriedDebuff|Parried] [Debuff] duration is {0} second",
				text="Parried Debuff duration is {0} second"
			},
			[3]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[ParriedDebuff|Parried] [Debuff] duration is {0} seconds",
				text="Parried Debuff duration is {0} seconds"
			}
		},
		stats={
			[1]="base_parry_duration_ms"
		}
	},
	[8]={
		[1]={
		},
		stats={
			[1]="parry_buff_attack_damage_taken_+%_final_magnitude_to_apply"
		}
	},
	[9]={
		[1]={
		},
		stats={
			[1]="parry_buff_spell_damage_taken_+%_final_magnitude_to_apply"
		}
	},
	[10]={
		[1]={
		},
		stats={
			[1]="virtual_parry_duration_ms"
		}
	},
	["base_parry_buff_damage_taken_+%_final_to_apply"]=6,
	["base_parry_duration_ms"]=7,
	["base_skill_effect_duration"]=2,
	["display_statset_no_hit_damage"]=1,
	parent="skill_stat_descriptions",
	["parry_buff_attack_damage_taken_+%_final_magnitude_to_apply"]=8,
	["parry_buff_spell_damage_taken_+%_final_magnitude_to_apply"]=9,
	["runic_fortress_stun_threshold_+%_final"]=3,
	["runic_fortress_stun_threshold_+%_final_per_10_ward_spent"]=4,
	["secondary_skill_effect_duration"]=5,
	["virtual_parry_duration_ms"]=10
}