-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="{0:+d} second to [MonsterModifiers|Modifier] duration",
				text="{0:+d} second to Modifier duration"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="{0:+d} seconds to [MonsterModifiers|Modifier] duration",
				text="{0:+d} seconds to Modifier duration"
			},
			[3]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[MonsterModifiers|Modifier] duration is {0} second",
				text="Modifier duration is {0} second"
			},
			[4]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[MonsterModifiers|Modifier] duration is {0} seconds",
				text="Modifier duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration",
			[2]="quality_display_base_skill_effect_duration_is_gem"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="When used on yourself, removes {0}% of maximum Life to grant a random [MonsterModifiers|Monster Modifier], replacing any previous\n[MonsterModifiers|Modifier] gained this way",
				text="When used on yourself, removes {0}% of maximum Life to grant a random Monster Modifier, replacing any previous\nModifier gained this way"
			}
		},
		stats={
			[1]="head_hunt_%_life_to_remove_on_self_stab"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["base_skill_effect_duration"]=1,
	["head_hunt_%_life_to_remove_on_self_stab"]=2,
	parent="skill_stat_descriptions",
	["quality_display_base_skill_effect_duration_is_gem"]=1,
	["skill_effect_duration"]=3
}