-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain {0} additional Fury on [Attack] [HitDamage|Hit]",
				text="Gain {0} additional Fury on Attack Hit"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain 1 Fury on [Attack] [HitDamage|Hit], no\nmore than once per Skill use",
				text="Gain 1 Fury on Attack Hit, no\nmore than once per Skill use"
			}
		},
		stats={
			[1]="wild_beast_energy_per_hit"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0} maximum Fury",
				text="{0} maximum Fury"
			}
		},
		stats={
			[1]="wild_beast_maximum_energy"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Buff] duration is {0} second per Fury",
				text="Buff duration is {0} second per Fury"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Buff] duration is {0} seconds per Fury",
				text="Buff duration is {0} seconds per Fury"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[4]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Buff] grants {0}% more damage",
				text="Buff grants {0}% more damage"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Buff] grants [Onslaught] and {0}% more damage",
				text="Buff grants Onslaught and {0}% more damage"
			}
		},
		stats={
			[1]="wild_beast_damage_+%_final"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Buff] grants {0}% increased [Attack] speed",
				text="Buff grants {0}% increased Attack speed"
			}
		},
		stats={
			[1]="wild_beast_attack_speed_+%"
		}
	},
	[6]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Buff] grants {0}% increased movement speed",
				text="Buff grants {0}% increased movement speed"
			}
		},
		stats={
			[1]="wild_beast_movement_speed_+%"
		}
	},
	[7]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Buff] causes you to lose {0}% of maximum Life per second",
				text="Buff causes you to lose {0}% of maximum Life per second"
			}
		},
		stats={
			[1]="wild_beast_life_lost_%_per_minute_nonlethal"
		}
	},
	[8]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	["base_skill_effect_duration"]=3,
	["skill_effect_duration"]=8,
	["wild_beast_attack_speed_+%"]=5,
	["wild_beast_damage_+%_final"]=4,
	["wild_beast_energy_per_hit"]=1,
	["wild_beast_life_lost_%_per_minute_nonlethal"]=7,
	["wild_beast_maximum_energy"]=2,
	["wild_beast_movement_speed_+%"]=6
}