-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Projectile] [Chain|Chains] an additional time on first hitting a [Shock|Shocked] or [Electrocute|Electrocuted] enemy, releasing a Shockwave on each [HitDamage|Hit]",
				text="Projectile Chains an additional time on first hitting a Shocked or Electrocuted enemy, releasing a Shockwave on each Hit"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Projectile] [Chain|Chains] {0} additional times on first hitting a [Shock|Shocked] or [Electrocute|Electrocuted] enemy, releasing a Shockwave on each [HitDamage|Hit]",
				text="Projectile Chains {0} additional times on first hitting a Shocked or Electrocuted enemy, releasing a Shockwave on each Hit"
			}
		},
		stats={
			[1]="shockchain_arrow_X_additional_chains_on_first_hitting_shocked_or_electrocuted_enemy"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Arrow duration is {0} second",
				text="Arrow duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Arrow duration is {0} seconds",
				text="Arrow duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Arrow disappears after being [Chain|Chained] to once",
				text="Arrow disappears after being Chained to once"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Arrow disappears after being [Chain|Chained] to {0} times",
				text="Arrow disappears after being Chained to {0} times"
			}
		},
		stats={
			[1]="lightning_rod_number_of_chains_allowed"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Maximum {0} active Arrow",
				text="Maximum {0} active Arrow"
			},
			[2]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Maximum {0} active Arrows",
				text="Maximum {0} active Arrows"
			}
		},
		stats={
			[1]="number_of_lightning_rods_allowed"
		}
	},
	[5]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	[6]={
		[1]={
		},
		stats={
			[1]="virtual_lightning_rod_number_of_chains_allowed"
		}
	},
	["base_skill_effect_duration"]=2,
	["lightning_rod_number_of_chains_allowed"]=3,
	["number_of_lightning_rods_allowed"]=4,
	parent="skill_stat_descriptions",
	["shockchain_arrow_X_additional_chains_on_first_hitting_shocked_or_electrocuted_enemy"]=1,
	["skill_effect_duration"]=5,
	["virtual_lightning_rod_number_of_chains_allowed"]=6
}