-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				rawText="[DNT-UNUSED] Shockwave radius is {0} metre",
				text="DNT-UNUSED Shockwave radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Shockwave radius is {0} metres",
				text="DNT-UNUSED Shockwave radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				rawText="[DNT-UNUSED] Spectral Bells can appear within {0} metre of you",
				text="DNT-UNUSED Spectral Bells can appear within {0} metre of you"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Spectral Bells can appear within {0} metres of you",
				text="DNT-UNUSED Spectral Bells can appear within {0} metres of you"
			}
		},
		stats={
			[1]="active_skill_base_secondary_area_of_effect_radius"
		}
	},
	[4]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[DNT-UNUSED] Spectral Bells linger for {0} second",
				text="DNT-UNUSED Spectral Bells linger for {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Spectral Bells linger for {0} seconds",
				text="DNT-UNUSED Spectral Bells linger for {0} seconds"
			}
		},
		stats={
			[1]="base_secondary_skill_effect_duration"
		}
	},
	[5]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] {0} second duration between Spectral Bells appearing",
				text="DNT-UNUSED {0} second duration between Spectral Bells appearing"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[6]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[DNT-UNUSED] Maximum {0} active Spectral Bell",
				text="DNT-UNUSED Maximum {0} active Spectral Bell"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Maximum {0} active Spectral Bells",
				text="DNT-UNUSED Maximum {0} active Spectral Bells"
			}
		},
		stats={
			[1]="spectral_bells_maximum_active_bells"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	["active_skill_base_secondary_area_of_effect_radius"]=3,
	["base_secondary_skill_effect_duration"]=4,
	["base_skill_effect_duration"]=5,
	parent="skill_stat_descriptions",
	["spectral_bells_maximum_active_bells"]=6
}