-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Cannot be cast if you have less than {0} Mana\nCannot be cast if already active",
				text="Cannot be cast if you have less than {0} Mana\nCannot be cast if already active"
			}
		},
		stats={
			[1]="mana_required_to_activate_skill"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Targeting radius is {0} metre",
				text="Targeting radius is {0} metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Targeting radius is {0} metres",
				text="Targeting radius is {0} metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Trigger|Triggers] Starfall every second, targeting enemies if able",
				text="Triggers Starfall every second, targeting enemies if able"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Trigger|Triggers] Starfall every {0} seconds, targeting enemies if able",
				text="Triggers Starfall every {0} seconds, targeting enemies if able"
			}
		},
		stats={
			[1]="walking_calamity_spawn_meteor_every_ms"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased Starfall [Trigger] frequency per enemy in radius after the first, up to a maximum of {1}%",
				text="{0}% increased Starfall Trigger frequency per enemy in radius after the first, up to a maximum of {1}%"
			}
		},
		stats={
			[1]="walking_calamity_meteor_frequency_+%_per_enemy_in_walking_calamity_radius",
			[2]="walking_calamity_meteor_frequency_+%_cap"
		}
	},
	[5]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} Starfall [Trigger|Triggers] required per large star",
				text="{0:+d} Starfall Triggers required per large star"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Starfall creates a large star every {0} times [Trigger|Triggered]",
				text="Starfall creates a large star every {0} times Triggered"
			}
		},
		stats={
			[1]="walking_calamity_large_meteor_every"
		}
	},
	[6]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[7]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Cannot [Trigger] Starfall for more than one large star per target every {0} second",
				text="Cannot Trigger Starfall for more than one large star per target every {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Starfall cannot cannot target the same enemy with large stars more than once every {0} seconds",
				text="Starfall cannot cannot target the same enemy with large stars more than once every {0} seconds"
			}
		},
		stats={
			[1]="walking_calamity_large_meteor_same_target_prevention_duration_ms"
		}
	},
	["active_skill_area_of_effect_radius"]=6,
	["active_skill_base_area_of_effect_radius"]=2,
	["mana_required_to_activate_skill"]=1,
	parent="skill_stat_descriptions",
	["walking_calamity_large_meteor_every"]=5,
	["walking_calamity_large_meteor_same_target_prevention_duration_ms"]=7,
	["walking_calamity_meteor_frequency_+%_cap"]=4,
	["walking_calamity_meteor_frequency_+%_per_enemy_in_walking_calamity_radius"]=4,
	["walking_calamity_spawn_meteor_every_ms"]=3
}