-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="Maximum [Buff] duration is {0} second",
				text="Maximum Buff duration is {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Maximum [Buff] duration is {0} seconds",
				text="Maximum Buff duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[2]={
		[1]={
		},
		stats={
			[1]="skill_effect_duration"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0}% of [Empowered] Skill's cast time is added to this Skill's cooldown",
				text="{0}% of Empowered Skill's cast time is added to this Skill's cooldown"
			}
		},
		stats={
			[1]="staff_unleash_cooldown_%_of_cast_time"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Empowered] [Spell] [Repeat|Repeats] {0} additional time",
				text="Empowered Spell Repeats {0} additional time"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Empowered] [Spell] [Repeat|Repeats] {0} times",
				text="Empowered Spell Repeats {0} times"
			}
		},
		stats={
			[1]="staff_unleash_number_of_seals_for_next_skill"
		}
	},
	["base_skill_effect_duration"]=1,
	parent="skill_stat_descriptions",
	["skill_effect_duration"]=2,
	["staff_unleash_cooldown_%_of_cast_time"]=3,
	["staff_unleash_number_of_seals_for_next_skill"]=4
}