-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Trigger] Manifest Rune on [HitDamage|Hitting] with an [Attack]",
				text="Trigger Manifest Rune on Hitting with an Attack"
			}
		},
		stats={
			[1]="skill_specific_stat_description_mode"
		}
	},
	parent="skill_stat_descriptions",
	["skill_specific_stat_description_mode"]=1
}