-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
		},
		stats={
			[1]="active_skill_area_of_effect_radius"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=10,
						[2]=10
					}
				},
				rawText="[DNT-UNUSED] Stag Hoofbeat radius is {0} Metre",
				text="DNT-UNUSED Stag Hoofbeat radius is {0} Metre"
			},
			[2]={
				[1]={
					k="divide_by_ten_1dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Stag Hoofbeat radius is {0} Metres",
				text="DNT-UNUSED Stag Hoofbeat radius is {0} Metres"
			}
		},
		stats={
			[1]="active_skill_base_area_of_effect_radius"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[DNT-UNUSED] Stags charge for {0} Hoofbeat",
				text="DNT-UNUSED Stags charge for {0} Hoofbeat"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Stags charge for {0} Hoofbeats",
				text="DNT-UNUSED Stags charge for {0} Hoofbeats"
			}
		},
		stats={
			[1]="vivid_stag_cascade_number_of_damaging_areas"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[DNT-UNUSED] Maximum {0} Vivid Stag wisp",
				text="DNT-UNUSED Maximum {0} Vivid Stag wisp"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Maximum {0} Vivid Stag wisps",
				text="DNT-UNUSED Maximum {0} Vivid Stag wisps"
			}
		},
		stats={
			[1]="vivid_stag_maximum_stag_wisps_allowed"
		}
	},
	["active_skill_area_of_effect_radius"]=1,
	["active_skill_base_area_of_effect_radius"]=2,
	parent="skill_stat_descriptions",
	["vivid_stag_cascade_number_of_damaging_areas"]=3,
	["vivid_stag_maximum_stag_wisps_allowed"]=4
}