-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Wardbound [Minion] [Limit]",
				text="{0:+d} to Wardbound Minion Limit"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Limit] {0} Summoned Wardbound [Minion]",
				text="Limit {0} Summoned Wardbound Minion"
			},
			[3]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Limit] {0} Summoned Wardbound [Minion|Minions]",
				text="Limit {0} Summoned Wardbound Minions"
			}
		},
		stats={
			[1]="base_number_of_wardbound_minions_allowed"
		}
	},
	[2]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d}s to [Minion] duration",
				text="{0:+d}s to Minion duration"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Minion] duration is {0} second",
				text="Minion duration is {0} second"
			},
			[3]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Minion] duration is {0} seconds",
				text="Minion duration is {0} seconds"
			}
		},
		stats={
			[1]="base_skill_effect_duration"
		}
	},
	[3]={
		[1]={
		},
		stats={
			[1]="minion_duration"
		}
	},
	[4]={
		[1]={
			[1]={
				["gem_quality"]=true,
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} [Spell|Spell] casts before dispersing",
				text="{0:+d} Spell casts before dispersing"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Minion|Minions] disperse after casting {0} [Spell|Spells]",
				text="Minions disperse after casting {0} Spells"
			},
			[3]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Minion|Minions] disperse after casting {0} [Spell|Spells]",
				text="Minions disperse after casting {0} Spells"
			}
		},
		stats={
			[1]="wardbound_minion_maximum_number_of_casts"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Summon one Wardbound [Minion] on Skill use and an additional [Minion] for each additional {0} [Ward|Runic Ward] spent",
				text="Summon one Wardbound Minion on Skill use and an additional Minion for each additional {0} Runic Ward spent"
			}
		},
		stats={
			[1]="wardbound_minions_summon_minion_for_every_X_runic_ward_spent"
		}
	},
	["base_number_of_wardbound_minions_allowed"]=1,
	["base_skill_effect_duration"]=2,
	["minion_duration"]=3,
	parent="skill_stat_descriptions",
	["wardbound_minion_maximum_number_of_casts"]=4,
	["wardbound_minions_summon_minion_for_every_X_runic_ward_spent"]=5
}