---@module "Modules.Utils"
local utils = LoadModule("../Modules/Utils")
local out = io.open("../Data/Misc.lua", "w")
out:write("-- This file is automatically generated, do not edit!\n\n")
out:write('---@class MiscDataExport\n')
out:write('local data = {}\n')
local evasion = ""
local accuracy = ""
local life = ""
local allyLife = ""
local allyDamage = ""
local damage = ""
local armour = ""
local ailmentThreshold = ""
local poiseThreshold = ""
local minionLevel = ""
for stats in dat("DefaultMonsterStats"):Rows() do
	evasion = evasion .. stats.Evasion .. ", "
	accuracy = accuracy .. stats.Accuracy .. ", "
	life = life .. stats.MonsterLife .. ", "
	allyLife = allyLife .. stats.MinionLife .. ", "
	damage = damage .. stats.Damage .. ", "
	allyDamage = allyDamage .. stats.MinionDamage .. ", "
	armour = armour .. stats.Armour .. ", "
	ailmentThreshold = ailmentThreshold .. stats.AilmentThreshold .. ", "
	poiseThreshold = poiseThreshold .. stats.PoiseThreshold .. ", "
end
-- Table was incorrect is PoE 1 but seems to be correct for PoE 2. Keeping here just in case
--for i = 1, 100 do
	--armour = armour .. math.floor((dat("GameConstants"):GetRow("Id", "MonsterArmourBase").Value + 2.5 * i ) * ( ( 1 + dat("GameConstants"):GetRow("Id", "MonsterArmourImprovement").Value / dat("GameConstants"):GetRow("Id", "MonsterArmourImprovement").Divisor / 100 ) ^ i)) .. ", "
--end
out:write('-- From DefaultMonsterStats.dat\n')
out:write('data.monsterEvasionTable = { '..evasion..'}\n') --This table is off by about 0.5% in some cases but is quicker than generating the value at runtime
out:write('data.monsterAccuracyTable = { '..accuracy..'}\n')
out:write('data.monsterLifeTable = { '..life..'}\n')
out:write('data.monsterAllyLifeTable = { '..allyLife..'}\n')
out:write('data.monsterDamageTable = { '..damage..'}\n')
out:write('data.monsterAllyDamageTable = { '..allyDamage..'}\n')
out:write('data.monsterArmourTable = { '..armour..'}\n')
out:write('data.monsterAilmentThresholdTable = { '..ailmentThreshold..'}\n')
out:write('data.monsterPoiseThresholdTable = { '..poiseThreshold..'}\n')
out:write('\n')

out:write('-- From MinionGemLevelScaling.dat\n')
for level in dat("MinionGemLevelScaling"):Rows() do
		minionLevel = minionLevel .. level.MinionLevel .. ", "
end
out:write('data.minionLevelTable = { '..minionLevel..'}\n')
out:write('\n')

out:write('-- From GameConstants.dat\n')
out:write('data.gameConstants = {\n')
for row in dat("GameConstants"):Rows() do
	out:write('\t["' .. row.Id .. '"] = ' .. row.Value / row.Divisor .. ',\n')
end
out:write('}\n')

out:write('-- From Metadata/Characters/Character.ot\n')
out:write('data.characterConstants = {\n')
local file = getFile("Metadata/Characters/Character.ot")
if not file then return nil end
local text = convertUTF16to8(file)
local inWantedBlock = false
for line in text:gmatch("[^\r\n]+") do
	-- Detect start of a block
	if line:match("^Stats") or line:match("^Pathfinding") then
		inWantedBlock = true
	elseif inWantedBlock and line:match("^}") then
		inWantedBlock = false
	elseif inWantedBlock and line:find("=") then
		local key, value = line:gsub("%s+",""):match("^(.-)=(.+)$")
		if key and value then
			out:write('\t["' .. key .. '"] = ' .. value .. ',\n')
		end
	end
end
out:write('}\n')

out:write('-- From Metadata/Monsters/Monster.ot\n')
out:write('data.monsterConstants = {\n')
local file = getFile("Metadata/Monsters/Monster.ot")
if not file then return nil end
local text = convertUTF16to8(file)
local inWantedBlock = false
for line in text:gmatch("[^\r\n]+") do
	-- Detect start of a block
	if line:match("^Stats") then
		inWantedBlock = true
	elseif inWantedBlock and line:match("^}") then
		inWantedBlock = false
	elseif inWantedBlock and line:find("=") then
		local key, value = line:gsub("%s+",""):match("^(.-)=(.+)$")
		if key and value then
			out:write('\t["' .. key .. '"] = ' .. value .. ',\n')
		end
	end
end
out:write('}\n')

out:write('-- From PlayerMinionIntrinsicStats.dat\n')
out:write('data.playerMinionIntrinsicStats = {\n')
for row in dat("PlayerMinionIntrinsicStats"):Rows() do
	out:write('\t["' .. row.Id.Id .. '"] = ' .. row.Value .. ',\n')
end
out:write('}\n')

local totemMult = ""
local keys = { }
for var in dat("SkillTotemVariations"):Rows() do
	if not keys[var.SkillTotem] then
		keys[var.SkillTotem] = true
		totemMult = totemMult .. "[" .. var.SkillTotem .. "] = " .. ((var.MonsterVariety and var.MonsterVariety.LifeMultiplier / 100) or 1) .. ", "
	end
end
out:write('-- From MonsterVarieties.dat combined with SkillTotemVariations.dat\n')
out:write('data.totemLifeMult = { '..totemMult..'}\n')

--[[out:write('-- From ActiveSkillType.dat\n') --Export list for use in Global.lua
out:write('data.skillTypeMap = {\n')
local skillTypeMap = { }
for row in dat("ActiveSkillType"):Rows() do
	out:write('\t' .. row.Id .. ' = ' .. row._rowIndex .. ',\n')
end
out:write('}\n')]]

out:write('data.monsterVarietyLifeMult = {\n')
local cachedEntry = { }
for row in dat("MonsterVarieties"):Rows() do
	for _, mod in ipairs(row.Mods) do
		if mod.Id == "MonsterNecromancerRaisable" and not cachedEntry['"' .. row.Name .. '"'] then
			out:write('\t["' .. row.Name .. '"] = ' .. row.LifeMultiplier/100 .. ',\n')
			cachedEntry['"' .. row.Name .. '"'] = true
			break
		end
	end
end
out:write('}\n')

out:write('-- From MonsterMapDifficulty.dat\n')
out:write('data.mapLevelLifeMult = { ')
for row in dat("MonsterMapDifficulty"):Rows() do
	out:write('[' .. row.AreaLevel .. '] = ' .. (1+row.LifePercentIncrease/100) .. ', ')
end
out:write('}\n')

local mapBossLifeMult = ""
local mapBossAilmentMult = ""
for var in dat("MonsterMapBossDifficulty"):Rows() do
	mapBossLifeMult = mapBossLifeMult .. "[" .. var.AreaLevel .. "] = " .. 1 + var.BossLifePercentIncrease / 100 .. ", "
	mapBossAilmentMult = mapBossAilmentMult .. "[" .. var.AreaLevel .. "] = " .. (100 + var.BossAilmentPercentDecrease) / 100 .. ", "
end

out:write('-- From MonsterMapBossDifficulty.dat\n')
out:write('data.mapLevelBossLifeMult = { '..mapBossLifeMult..'}\n')
out:write('data.mapLevelBossAilmentMult = { '..mapBossAilmentMult..'}\n')
out:write('\n')

out:write('-- From FlatPhysicalDamageValues.dat\n')
out:write('data.hollowPalmAddedPhys = {\n')
for row in dat("FlatPhysicalDamageValues"):Rows() do
	out:write('\t[' .. row.Level .. '] = { ' .. row.MinPhys .. ', ' .. row.MaxPhys .. ' },\n')
end
out:write('}\n')

out:write('-- From GoldRespecPrices.dat\n')
out:write('data.goldRespecPrices = { ')
for row in dat("GoldRespecPrices"):Rows() do
	out:write(row.Cost .. ', ')
end
out:write('}\n')

out:write('return data\n')
out:close()

local currencies = {}
for row in dat("BaseItemTypes"):Rows() do
	if row.ItemClass.Id == "StackableCurrency" and row.Name ~= "" then
		currencies[row.Id] = row.Name
	end
end
utils.saveTableToFile("../Data/CurrencyNames.lua", currencies, "This file contains mapping item names for every currency base item type ID.\nUsed for working with the currency exchange which uses item type IDs.")

local characterMeleeSkills = { }
for row in dat("CharacterMeleeSkills"):Rows() do
	local mainHand = row.MainHandItem.ItemClass.Id
	local offHand = row.OffHandItem.ItemClass.Id
	local skillGems = { }
	for _, skillGem in ipairs(row.SkillGem) do
		skillGems[#skillGems + 1] = skillGem.BaseItemType.Id
	end
	characterMeleeSkills[mainHand] = characterMeleeSkills[mainHand] or { }
	characterMeleeSkills[mainHand][offHand] = skillGems
end
utils.saveTableToFile("../Data/CharacterMeleeSkills.lua", characterMeleeSkills, "Default skill gem base item IDs keyed by main-hand and off-hand WieldableClasses item class IDs.")

local verisiumCrafts = {}
for row in dat("Expedition2VerisiumCrafts"):Rows() do
	local sourceBase = row.OriginalBaseType.Name
	if not verisiumCrafts[sourceBase] then
		verisiumCrafts[sourceBase] = {}
	end
	table.insert(verisiumCrafts[sourceBase], { baseTypeId = row.NewBaseType.Id, name = row.NewBaseType.Name })
end
utils.saveTableToFile("../Data/VerisiumCrafts.lua", verisiumCrafts, "A list of possible base type transformations in runeforging/mastering.")
print("Misc data exported.")
