-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
			return {

{
name = "Ruby",
	type = "Jewel",
	tags = { default = true, jewel = true, strjewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Emerald",
	type = "Jewel",
	tags = { default = true, dexjewel = true, jewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Sapphire",
	type = "Jewel",
	tags = { default = true, intjewel = true, jewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Diamond",
	type = "Jewel",
	tags = { default = true, dexjewel = true, intjewel = true, jewel = true, not_for_sale = true, strjewel = true, },
	implicitModTypes = { },
	req = { },
},

{
name = "Time-Lost Ruby",
	type = "Jewel",
	subType = "Radius",
	tags = { default = true, jewel = true, not_for_sale = true, radius_jewel = true, str_radius_jewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Time-Lost Emerald",
	type = "Jewel",
	subType = "Radius",
	tags = { default = true, dex_radius_jewel = true, jewel = true, not_for_sale = true, radius_jewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Time-Lost Sapphire",
	type = "Jewel",
	subType = "Radius",
	tags = { default = true, int_radius_jewel = true, jewel = true, not_for_sale = true, radius_jewel = true, },
	implicitModTypes = { },
	req = { },
},
{
name = "Time-Lost Diamond",
	type = "Jewel",
	subType = "Radius",
	tags = { default = true, dex_radius_jewel = true, int_radius_jewel = true, jewel = true, not_for_sale = true, radius_jewel = true, str_radius_jewel = true, },
	implicitModTypes = { },
	req = { },
},

{
name = "Timeless Jewel",
	type = "Jewel",
	subType = "Timeless",
	hidden = true,
	tags = { default = true, dexjewel = true, intjewel = true, jewel = true, not_for_sale = true, strjewel = true, },
	implicitModTypes = { },
	req = { },
},
			}
