-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games

return {
	[1]={
		stats={
			[1]="damage_taken_+%_from_hits"
		}
	},
	[2]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Devotion",
				text="{0:+d} to Devotion"
			}
		},
		stats={
			[1]="base_devotion"
		}
	},
	[3]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Tribute",
				text="{0:+d} to Tribute"
			}
		},
		stats={
			[1]="base_tribute"
		}
	},
	[4]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased Tribute",
				text="{0}% increased Tribute"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced Tribute",
				text="{0}% reduced Tribute"
			}
		},
		stats={
			[1]="tribute_+%"
		}
	},
	[5]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Strength]",
				text="{0:+d} to Strength"
			}
		},
		stats={
			[1]="base_strength"
		}
	},
	[6]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Strength]",
				text="{0}% increased Strength"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Strength]",
				text="{0}% reduced Strength"
			}
		},
		stats={
			[1]="strength_+%"
		}
	},
	[7]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Dexterity]",
				text="{0:+d} to Dexterity"
			}
		},
		stats={
			[1]="base_dexterity"
		}
	},
	[8]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Dexterity]",
				text="{0}% increased Dexterity"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Dexterity]",
				text="{0}% reduced Dexterity"
			}
		},
		stats={
			[1]="dexterity_+%"
		}
	},
	[9]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Intelligence]",
				text="{0:+d} to Intelligence"
			}
		},
		stats={
			[1]="base_intelligence"
		}
	},
	[10]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Intelligence]",
				text="{0}% increased Intelligence"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Intelligence]",
				text="{0}% reduced Intelligence"
			}
		},
		stats={
			[1]="intelligence_+%"
		}
	},
	[11]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Regenerate {0}% of maximum Mana per second",
				text="Regenerate {0}% of maximum Mana per second"
			}
		},
		stats={
			[1]="mana_regeneration_rate_per_minute_%"
		}
	},
	[12]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Regenerate {0}% of maximum Mana per second per Power Charge",
				text="Regenerate {0}% of maximum Mana per second per Power Charge"
			}
		},
		stats={
			[1]="mana_regeneration_rate_per_minute_%_per_power_charge"
		}
	},
	[13]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum [Charges|Endurance Charges]",
				text="{0:+d} to Maximum Endurance Charges"
			}
		},
		stats={
			[1]="max_endurance_charges"
		}
	},
	[14]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum [Charges|Frenzy Charges]",
				text="{0:+d} to Maximum Frenzy Charges"
			}
		},
		stats={
			[1]="max_frenzy_charges"
		}
	},
	[15]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum [Charges|Power Charges]",
				text="{0:+d} to Maximum Power Charges"
			}
		},
		stats={
			[1]="max_power_charges"
		}
	},
	[16]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased Physical Damage per Frenzy Charge",
				text="{0}% increased Physical Damage per Frenzy Charge"
			}
		},
		stats={
			[1]="physical_damage_+%_per_frenzy_charge"
		}
	},
	[17]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Gain a [Charges|Frenzy Charge] on kill",
				text="Gain a Frenzy Charge on kill"
			}
		},
		stats={
			[1]="add_frenzy_charge_on_kill"
		}
	},
	[18]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[StatConversion|Converts] all [Evasion|Evasion Rating] to [Armour]",
				text="Converts all Evasion Rating to Armour"
			}
		},
		stats={
			[1]="keystone_iron_reflexes"
		}
	},
	[19]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="75% of Damage Converted to Fire Damage\nDeal no Non-Fire Damage",
				text="75% of Damage Converted to Fire Damage\nDeal no Non-Fire Damage"
			}
		},
		stats={
			[1]="keystone_avatar_of_fire"
		}
	},
	[20]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[StatConversion|Convert] 100% of maximum [EnergyShield|Energy Shield] to maximum Mana\nMana Costs are Doubled",
				text="Convert 100% of maximum Energy Shield to maximum Mana\nMana Costs are Doubled"
			}
		},
		stats={
			[1]="keystone_eldritch_battery"
		}
	},
	[21]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Your [Totem] [Limit] is doubled\nNo [Charges|Charge] requirement for placing [Totem|Totems]\n[Totem|Totems] reserve 75 [Spirit] each",
				text="Your Totem Limit is doubled\nNo Charge requirement for placing Totems\nTotems reserve 75 Spirit each"
			}
		},
		stats={
			[1]="keystone_ancestral_bond"
		}
	},
	[22]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum number of Spectres",
				text="{0:+d} to Maximum number of Spectres"
			}
		},
		stats={
			[1]="base_number_of_spectres_allowed"
		}
	},
	[23]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum number of Skeletons",
				text="{0:+d} to Maximum number of Skeletons"
			}
		},
		stats={
			[1]="base_number_of_skeletons_allowed"
		}
	},
	[24]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum number of Summoned Raging Spirits",
				text="{0:+d} to Maximum number of Summoned Raging Spirits"
			}
		},
		stats={
			[1]="base_number_of_raging_spirits_allowed"
		}
	},
	[25]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Can [Evasion|Evade] all Hits\n75% less [Evasion] Rating",
				text="Can Evade all Hits\n75% less Evasion Rating"
			}
		},
		stats={
			[1]="keystone_acrobatics"
		}
	},
	[26]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="30% less [CriticalDamageBonus|Critical Damage Bonus] when on Full Life\n30% more Critical Damage Bonus when on [LowLife|Low Life]",
				text="30% less Critical Damage Bonus when on Full Life\n30% more Critical Damage Bonus when on Low Life"
			}
		},
		stats={
			[1]="keystone_pain_attunement"
		}
	},
	[27]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Projectile [Attack] Hits deal up to 30% more Damage to targets at the start of their movement, dealing less Damage to targets as the projectile travels farther",
				text="Projectile Attack Hits deal up to 30% more Damage to targets at the start of their movement, dealing less Damage to targets as the projectile travels farther"
			}
		},
		stats={
			[1]="keystone_point_blank"
		}
	},
	[28]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="If you would gain a [Charges|Charge], [Allies] in your [Presence] gain that [Charges|Charge] instead",
				text="If you would gain a Charge, Allies in your Presence gain that Charge instead"
			}
		},
		stats={
			[1]="keystone_conduit"
		}
	},
	[29]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You have no Mana\nSkill Mana Costs [StatConversion|Converted] to Life Costs",
				text="You have no Mana\nSkill Mana Costs Converted to Life Costs"
			}
		},
		stats={
			[1]="keystone_blood_magic"
		}
	},
	[30]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Minions Explode when reduced to [LowLife|Low Life], dealing 33% of their Life as Fire Damage to surrounding Enemies",
				text="Minions Explode when reduced to Low Life, dealing 33% of their Life as Fire Damage to surrounding Enemies"
			}
		},
		stats={
			[1]="keystone_minion_instability"
		}
	},
	[31]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Create [Lightning] [ElementalInfusion|Infusion] [Remnant|Remnants] instead of [Fire]\nCreate [Cold] [ElementalInfusion|Infusion] [Remnant|Remnants] instead of [Lightning]\nCreate [Fire] [ElementalInfusion|Infusion] [Remnant|Remnants] instead of [Cold]",
				text="Create Lightning Infusion Remnants instead of Fire\nCreate Cold Infusion Remnants instead of Lightning\nCreate Fire Infusion Remnants instead of Cold"
			}
		},
		stats={
			[1]="keystone_elemental_equilibrium"
		}
	},
	[32]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Maximum Life is 1\nImmune to [Chaos] Damage and [Bleeding]",
				text="Maximum Life is 1\nImmune to Chaos Damage and Bleeding"
			}
		},
		stats={
			[1]="keystone_chaos_inoculation"
		}
	},
	[33]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="50% more amount of [LifeLeech|Life Leeched]\n[LifeLeech|Leech Life] 67% less quickly\nCannot Recover Life other than from [LifeLeech|Leech]\n[LifeLeech|Life Leech] effects are not removed when [Reservation|Unreserved] Life is Filled",
				text="50% more amount of Life Leeched\nLeech Life 67% less quickly\nCannot Recover Life other than from Leech\nLife Leech effects are not removed when Unreserved Life is Filled"
			}
		},
		stats={
			[1]="keystone_vaal_pact"
		}
	},
	[34]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Critical|Critical Hit Chance]",
				text="{0}% increased Critical Hit Chance"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Critical|Critical Hit Chance]",
				text="{0}% reduced Critical Hit Chance"
			}
		},
		stats={
			[1]="critical_strike_chance_+%"
		}
	},
	[35]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d}% Chance to Block [Attack] Damage while wielding a Staff",
				text="{0:+d}% Chance to Block Attack Damage while wielding a Staff"
			}
		},
		stats={
			[1]="staff_block_%"
		}
	},
	[36]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="All [DamageTypes|Damage] is taken from Mana before Life\n50% less Mana Recovery Rate",
				text="All Damage is taken from Mana before Life\n50% less Mana Recovery Rate"
			}
		},
		stats={
			[1]="keystone_mana_shield"
		}
	},
	[37]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Accuracy] Rating is Doubled\nNever deal [Critical|Critical Hits]",
				text="Accuracy Rating is Doubled\nNever deal Critical Hits"
			}
		},
		stats={
			[1]="resolute_technique"
		}
	},
	[38]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Cannot be [LightStun|Light Stunned]\nCannot Dodge Roll or Sprint",
				text="Cannot be Light Stunned\nCannot Dodge Roll or Sprint"
			}
		},
		stats={
			[1]="keystone_unwavering_stance"
		}
	},
	[39]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Can be allocated without connection to the tree",
				text="Can be allocated without connection to the tree"
			}
		},
		stats={
			[1]="passive_can_be_allocated_without_connection"
		}
	},
	[40]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Strength|Strength] and [Dexterity|Dexterity]",
				text="{0:+d} to Strength and Dexterity"
			}
		},
		stats={
			[1]="base_strength_and_dexterity"
		}
	},
	[41]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Strength|Strength] and [Intelligence|Intelligence]",
				text="{0:+d} to Strength and Intelligence"
			}
		},
		stats={
			[1]="base_strength_and_intelligence"
		}
	},
	[42]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to [Dexterity|Dexterity] and [Intelligence|Intelligence]",
				text="{0:+d} to Dexterity and Intelligence"
			}
		},
		stats={
			[1]="base_dexterity_and_intelligence"
		}
	},
	[43]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]=99
					}
				},
				rawText="{0}% chance to [Blind] Enemies on [HitDamage|Hit]",
				text="{0}% chance to Blind Enemies on Hit"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				rawText="[Blind] Enemies on [HitDamage|Hit]",
				text="Blind Enemies on Hit"
			}
		},
		stats={
			[1]="global_chance_to_blind_on_hit_%"
		}
	},
	[44]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=0,
						[2]=0
					},
					[2]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Skills fire an additional [Projectile|Projectile]",
				text="Skills fire an additional Projectile"
			},
			[2]={
				limit={
					[1]={
						[1]=0,
						[2]=0
					},
					[2]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Skills fire {1} additional [Projectile|Projectiles]",
				text="Skills fire {1} additional Projectiles"
			}
		},
		stats={
			[1]="active_skill_additional_projectiles_description_mode",
			[2]="number_of_additional_projectiles"
		}
	},
	[45]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to maximum number of Summoned Golems",
				text="{0:+d} to maximum number of Summoned Golems"
			}
		},
		stats={
			[1]="base_number_of_golems_allowed"
		}
	},
	[46]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Can Allocate Passive Skills from the Warrior's starting point",
				text="Can Allocate Passive Skills from the Warrior's starting point"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]=2
					}
				},
				rawText="Can Allocate Passive Skills from the Ranger's starting point",
				text="Can Allocate Passive Skills from the Ranger's starting point"
			},
			[3]={
				limit={
					[1]={
						[1]=3,
						[2]=3
					}
				},
				rawText="Can Allocate Passive Skills from the Sorceress's starting point",
				text="Can Allocate Passive Skills from the Sorceress's starting point"
			},
			[4]={
				limit={
					[1]={
						[1]=4,
						[2]=4
					}
				},
				rawText="Can Allocate Passive Skills from the Mercenary's starting point",
				text="Can Allocate Passive Skills from the Mercenary's starting point"
			},
			[5]={
				limit={
					[1]={
						[1]=5,
						[2]=5
					}
				},
				rawText="Can Allocate Passive Skills from the Templar's starting point",
				text="Can Allocate Passive Skills from the Templar's starting point"
			},
			[6]={
				limit={
					[1]={
						[1]=6,
						[2]=6
					}
				},
				rawText="Can Allocate Passive Skills from the Shadow's starting point",
				text="Can Allocate Passive Skills from the Shadow's starting point"
			}
		},
		stats={
			[1]="display_can_take_character_start_point"
		}
	},
	[47]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=99
					}
				},
				rawText="{0}% chance to create [ConsecratedGround|Consecrated Ground] on kill, lasting 8 seconds",
				text="{0}% chance to create Consecrated Ground on kill, lasting 8 seconds"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				rawText="Create [ConsecratedGround|Consecrated Ground] on kill, lasting 8 seconds",
				text="Create Consecrated Ground on kill, lasting 8 seconds"
			}
		},
		stats={
			[1]="consecrate_ground_on_kill_%_for_3_seconds"
		}
	},
	[48]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="-{0} second to base [ESRecharge|Energy Shield Recharge] delay",
				text="-{0} second to base Energy Shield Recharge delay"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="-{0} seconds to base [ESRecharge|Energy Shield Recharge] delay",
				text="-{0} seconds to base Energy Shield Recharge delay"
			}
		},
		stats={
			[1]="energy_shield_recharge_starts_X_ms_sooner"
		}
	},
	[49]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="Gain {0} Life [Flask] Charge per 2% Life spent",
				text="Gain {0} Life Flask Charge per 2% Life spent"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="Gain {0} Life [Flask] Charges per 2% Life spent",
				text="Gain {0} Life Flask Charges per 2% Life spent"
			}
		},
		stats={
			[1]="gain_X_life_flask_charges_per_4%_life_spent"
		}
	},
	[50]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Armour], [Evasion] and [EnergyShield|Energy Shield]",
				text="{0}% increased Armour, Evasion and Energy Shield"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Armour], [Evasion] and [EnergyShield|Energy Shield]",
				text="{0}% reduced Armour, Evasion and Energy Shield"
			}
		},
		stats={
			[1]="global_armour_evasion_energy_shield_+%"
		}
	},
	[51]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Adaptation|Adaptations] have a duration of {0} second",
				text="Adaptations have a duration of {0} second"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Adaptation|Adaptations] have a duration of {0} seconds",
				text="Adaptations have a duration of {0} seconds"
			}
		},
		stats={
			[1]="adaptation_duration_ms"
		}
	},
	[52]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=1
					}
				},
				rawText="[Adaptation|Adapt] to the highest [ElementalDamage|Elemental Damage Type] of each [HitDamage|Hit] you take",
				text="Adapt to the highest Elemental Damage Type of each Hit you take"
			},
			[2]={
				limit={
					[1]={
						[1]=2,
						[2]="#"
					}
				},
				rawText="[Adaptation|Adapt] {0} times to the highest [ElementalDamage|Elemental Damage Type] of each [HitDamage|Hit] you take",
				text="Adapt {0} times to the highest Elemental Damage Type of each Hit you take"
			}
		},
		stats={
			[1]="gain_X_adaptation_matching_type_when_hit_by_elemental_damage"
		}
	},
	[53]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=99
					}
				},
				rawText="{0}% Chance to build an additional [Combo] on [HitDamage|Hit]",
				text="{0}% Chance to build an additional Combo on Hit"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				rawText="Build an additional [Combo] on [HitDamage|Hit]",
				text="Build an additional Combo on Hit"
			}
		},
		stats={
			[1]="additional_combo_gain_chance_%"
		}
	},
	[54]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Bleeding] you inflict on [Pinned] Enemies is [Aggravate|Aggravated]",
				text="Bleeding you inflict on Pinned Enemies is Aggravated"
			}
		},
		stats={
			[1]="aggravate_bleeding_when_inflicted_vs_pinned_enemy"
		}
	},
	[55]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [BuffEffect|Effect] of [ArcaneSurge|Arcane Surge] on you per ten percent missing Mana",
				text="{0}% increased Effect of Arcane Surge on you per ten percent missing Mana"
			}
		},
		stats={
			[1]="arcane_surge_effect_on_self_+%_per_10%_missing_mana"
		}
	},
	[56]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] {0}% more Mana cost of [Trigger|Triggered Skills]",
				text="DNT-UNUSED {0}% more Mana cost of Triggered Skills"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[DNT-UNUSED] {0}% less Mana cost of [Trigger|Triggered Skills]",
				text="DNT-UNUSED {0}% less Mana cost of Triggered Skills"
			}
		},
		stats={
			[1]="ascendancy_arcane_archer_triggered_skill_mana_cost_+%_final"
		}
	},
	[57]={
		[1]={
			[1]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="Enemies in your [Presence|Presence] are [Slow|Slowed] by {0}%",
				text="Enemies in your Presence are Slowed by {0}%"
			}
		},
		stats={
			[1]="ascendancy_chronomancer_apex_of_the_moment_base_slow_aura_value"
		}
	},
	[58]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Non-Keystone Passive Skills in Medium Radius of allocated Keystone Passive Skills can be allocated without being connected to your tree",
				text="Non-Keystone Passive Skills in Medium Radius of allocated Keystone Passive Skills can be allocated without being connected to your tree"
			}
		},
		stats={
			[1]="ascendancy_disconnected_passives_can_be_allocated_around_allocated_keystones"
		}
	},
	[59]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Grants [ThaumaturgicalDynamism|Thaumaturgical Dynamism]",
				text="Grants Thaumaturgical Dynamism"
			}
		},
		stats={
			[1]="ascendancy_gemling_charge_generator_buff_display"
		}
	},
	[60]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gem [Quality] grants Socketed Skills an additional effect",
				text="Gem Quality grants Socketed Skills an additional effect"
			}
		},
		stats={
			[1]="ascendancy_gemling_enable_thaumaturgy_quality_stats"
		}
	},
	[61]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Damaging [Spell|Spells] consume a [Charges|Power Charge] if able to trigger Abyssal Apparition",
				text="Damaging Spells consume a Power Charge if able to trigger Abyssal Apparition"
			}
		},
		stats={
			[1]="ascendancy_lich_consume_power_for_apparition"
		}
	},
	[62]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Skeletal [Minion|Minions] you would create instead grant you [LichSkeletalBuff|Umbral Souls] for each [Minion] you would have created",
				text="Skeletal Minions you would create instead grant you Umbral Souls for each Minion you would have created"
			}
		},
		stats={
			[1]="ascendancy_lich_skeletons_are_buffs_instead_of_minions"
		}
	},
	[63]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Spell|Spells] consume a [Charges|Power Charge] if able to deal {0}% more Damage",
				text="Spells consume a Power Charge if able to deal {0}% more Damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[Spell|Spells] consume a [Charges|Power Charge] if able to deal {0}% less Damage",
				text="Spells consume a Power Charge if able to deal {0}% less Damage"
			}
		},
		stats={
			[1]="ascendancy_lich_spells_consume_power_charges_for_spell_damage_+%_final"
		}
	},
	[64]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Walk the [OraclePaths|Paths Not Taken]",
				text="Walk the Paths Not Taken"
			}
		},
		stats={
			[1]="ascendancy_oracle_can_allocate_additional_oracle_only_passives_display"
		}
	},
	[65]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] [Ignite|Ignites] you inflict have up to {0}% more [BuffMagnitude|Magnitude], at random",
				text="DNT-UNUSED Ignites you inflict have up to {0}% more Magnitude, at random"
			}
		},
		stats={
			[1]="ascendancy_random_ignite_effect_+%_final_up_to_%"
		}
	},
	[66]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more Damage against Enemies affected by Blood Boils",
				text="{0}% more Damage against Enemies affected by Blood Boils"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less Damage against Enemies affected by Blood Boils",
				text="{0}% less Damage against Enemies affected by Blood Boils"
			}
		},
		stats={
			[1]="ascendancy_ritualist_damage_+%_final_vs_enemies_affected_by_blood_boil"
		}
	},
	[67]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain an additional {0} [Spirit] for each empty available [Charm] slot you have",
				text="Gain an additional {0} Spirit for each empty available Charm slot you have"
			}
		},
		stats={
			[1]="ascendancy_shaman_+_spirit_per_empty_charm_slot"
		}
	},
	[68]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Every 2 [Rage] also grants {0}% more [Spell] damage",
				text="Every 2 Rage also grants {0}% more Spell damage"
			}
		},
		stats={
			[1]="ascendancy_shaman_spell_damage_+%_final_per_2_rage"
		}
	},
	[69]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Cascadable|Cascadable] [Spell|Spells] have {0}% chance to [Cascadable|Echo]",
				text="Cascadable Spells have {0}% chance to Echo"
			}
		},
		stats={
			[1]="ascendancy_spell_deja_vu_skill_echo_chance_%"
		}
	},
	[70]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Repeat|Repeatable] [Spell|Spells] have {0}% chance to [Repeat]",
				text="Repeatable Spells have {0}% chance to Repeat"
			}
		},
		stats={
			[1]="ascendancy_spell_deja_vu_spell_%_chance_to_reoccur_an_additional_time"
		}
	},
	[71]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=-100,
						[2]=-100
					}
				},
				rawText="Cannot cause [Immobilised|Immobilisation] buildup",
				text="Cannot cause Immobilisation buildup"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more [Immobilised|Immobilisation] buildup",
				text="{0}% more Immobilisation buildup"
			},
			[3]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less [Immobilised|Immobilisation] buildup",
				text="{0}% less Immobilisation buildup"
			}
		},
		stats={
			[1]="ascendancy_tactician_suppressing_fire_hit_damage_immobilisation_multiplier_+%_final"
		}
	},
	[72]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Targets [Curse|Cursed] by you have at least {0}% of Life [Reservation|Reserved]",
				text="Targets Cursed by you have at least {0}% of Life Reserved"
			}
		},
		stats={
			[1]="ascendancy_whispers_of_the_flesh_cursed_enemies_have_at_least_life_reserved_%"
		}
	},
	[73]={
		[1]={
			[1]={
				[1]={
					k="per_minute_to_per_second_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Regenerate {0}% of your maximum [Rage] per second",
				text="Regenerate {0}% of your maximum Rage per second"
			}
		},
		stats={
			[1]="base_rage_regeneration_rate_per_minute_%"
		}
	},
	[74]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=3
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					},
					[3]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="On [HitDamage|Hitting] an Enemy while a Life [Flask] is at full Charges, {0}% of its Charges are consumed\n[Gain] {1}% of damage as [Physical] damage for {2} second per Charge consumed this way",
				text="On Hitting an Enemy while a Life Flask is at full Charges, {0}% of its Charges are consumed\nGain {1}% of damage as Physical damage for {2} second per Charge consumed this way"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=3
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					},
					[3]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="On [HitDamage|Hitting] an Enemy while a Life [Flask] is at full Charges, {0}% of its Charges are consumed\n[Gain] {1}% of damage as [Physical] damage for {2} seconds per Charge consumed this way",
				text="On Hitting an Enemy while a Life Flask is at full Charges, {0}% of its Charges are consumed\nGain {1}% of damage as Physical damage for {2} seconds per Charge consumed this way"
			}
		},
		stats={
			[1]="blood_mage_life_flask_buff_%_charges_to_consume",
			[2]="blood_mage_life_flask_buff_%_damage_to_gain_as_physical_per_charge_consumed",
			[3]="blood_mage_life_flask_buff_duration_ms"
		}
	},
	[75]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can equip a [Focus] while wielding a [Staff]",
				text="You can equip a Focus while wielding a Staff"
			}
		},
		stats={
			[1]="can_equip_staff_with_focus"
		}
	},
	[76]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Gain [Combo] from all [Attack] [HitDamage|Hits]",
				text="Gain Combo from all Attack Hits"
			}
		},
		stats={
			[1]="can_gain_combo_from_any_attack_hit"
		}
	},
	[77]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="All [FlamesOfChayula|Flames of Chayula] that you manifest are [BlueFlamesOfChayula|Blue]",
				text="All Flames of Chayula that you manifest are Blue"
			}
		},
		stats={
			[1]="can_only_spawn_blue_flame_of_chayula_remnants"
		}
	},
	[78]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="All [FlamesOfChayula|Flames of Chayula] that you manifest are [PurpleFlamesOfChayula|Purple]",
				text="All Flames of Chayula that you manifest are Purple"
			}
		},
		stats={
			[1]="can_only_spawn_purple_flame_of_chayula_remnants"
		}
	},
	[79]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="All [FlamesOfChayula|Flames of Chayula] that you manifest are [RedFlamesOfChayula|Red]",
				text="All Flames of Chayula that you manifest are Red"
			}
		},
		stats={
			[1]="can_only_spawn_red_flame_of_chayula_remnants"
		}
	},
	[80]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% chance for Damage with [HitDamage|Hits] to be [Lucky]",
				text="{0}% chance for Damage with Hits to be Lucky"
			}
		},
		stats={
			[1]="chance_for_extra_damage_roll_%"
		}
	},
	[81]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=99
					}
				},
				rawText="{0}% chance when collecting an [ElementalInfusion|Elemental Infusion] to gain another different [ElementalInfusion|Elemental Infusion]",
				text="{0}% chance when collecting an Elemental Infusion to gain another different Elemental Infusion"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]="#"
					}
				},
				rawText="When collecting an [ElementalInfusion|Elemental Infusion], gain another different [ElementalInfusion|Elemental Infusion]",
				text="When collecting an Elemental Infusion, gain another different Elemental Infusion"
			}
		},
		stats={
			[1]="chance_%_for_extra_infusion_on_infused_remnant_pickup"
		}
	},
	[82]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% chance to gain an Owl Feather on [Critical|Critical Hit]",
				text="{0}% chance to gain an Owl Feather on Critical Hit"
			}
		},
		stats={
			[1]="chance_to_generate_owl_feather_%_on_crit"
		}
	},
	[83]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Skills have {0}% chance to not remove [Charges|Charges] but still count as consuming them",
				text="Skills have {0}% chance to not remove Charges but still count as consuming them"
			}
		},
		stats={
			[1]="charge_skip_consume_chance_%"
		}
	},
	[84]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [BuffMagnitude|Magnitude] of [Chill] you inflict",
				text="{0}% increased Magnitude of Chill you inflict"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [BuffMagnitude|Magnitude] of [Chill] you inflict",
				text="{0}% reduced Magnitude of Chill you inflict"
			}
		},
		stats={
			[1]="chill_effect_+%"
		}
	},
	[85]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Take {0}% more Damage",
				text="Take {0}% more Damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="Take {0}% less Damage",
				text="Take {0}% less Damage"
			}
		},
		stats={
			[1]="chronomancer_damage_taken_+%_final"
		}
	},
	[86]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Grants [Chronobuff|Sands of Time]",
				text="Grants Sands of Time"
			}
		},
		stats={
			[1]="chronomancer_grant_cast_speed_+%",
			[2]="chronomancer_grant_area_of_effect_+%"
		}
	},
	[87]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="4 seconds after being Damaged by an Enemy [HitDamage|Hit], take Damage equal to {0}% of that [HitDamage|Hit]'s Damage",
				text="4 seconds after being Damaged by an Enemy Hit, take Damage equal to {0}% of that Hit's Damage"
			}
		},
		stats={
			[1]="chronomancer_take_%_of_hit_damage_4_seconds_after_being_hit"
		}
	},
	[88]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0}% chance for [Remnant|Remnants] you create to grant their effects twice",
				text="{0}% chance for Remnants you create to grant their effects twice"
			}
		},
		stats={
			[1]="created_remnants_have_%_chance_to_duplicate_pick_up_results"
		}
	},
	[89]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Enemy [Critical|Critical Hit Chance] against you is [Unlucky]",
				text="Enemy Critical Hit Chance against you is Unlucky"
			}
		},
		stats={
			[1]="critical_chance_vs_self_is_unlucky"
		}
	},
	[90]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Your [HitDamage|Hits] are [CrushingBlow|Crushing Blows]",
				text="Your Hits are Crushing Blows"
			}
		},
		stats={
			[1]="crushing_blow"
		}
	},
	[91]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]=99
					}
				},
				rawText="{0}% of Current [EnergyShield|Energy Shield] also grants [Physical|Physical Damage] reduction",
				text="{0}% of Current Energy Shield also grants Physical Damage reduction"
			},
			[2]={
				limit={
					[1]={
						[1]=100,
						[2]=100
					}
				},
				rawText="Current [EnergyShield|Energy Shield] also grants [Physical|Physical Damage] reduction",
				text="Current Energy Shield also grants Physical Damage reduction"
			},
			[3]={
				limit={
					[1]={
						[1]=101,
						[2]="#"
					}
				},
				rawText="{0}% of Current [EnergyShield|Energy Shield] also grants [Physical|Physical Damage] reduction",
				text="{0}% of Current Energy Shield also grants Physical Damage reduction"
			}
		},
		stats={
			[1]="current_energy_shield_%_as_elemental_damage_reduction"
		}
	},
	[92]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Damage of Enemies [HitDamage|Hitting] you is [Unlucky]",
				text="Damage of Enemies Hitting you is Unlucky"
			}
		},
		stats={
			[1]="damage_taken_from_hits_is_unlucky"
		}
	},
	[93]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0}% chance to [Daze] Enemies whose [HitDamage|Hits] you [Block] with a raised [Shield]",
				text="{0}% chance to Daze Enemies whose Hits you Block with a raised Shield"
			}
		},
		stats={
			[1]="daze_enemies_on_block_with_shield_raised_chance_%"
		}
	},
	[94]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Enable Living Bomb",
				text="DNT-UNUSED Enable Living Bomb"
			}
		},
		stats={
			[1]="display_fire_djinn_enable_living_bomb"
		}
	},
	[95]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Enemies within 2 metres of you are Taunted",
				text="Enemies within 2 metres of you are Taunted"
			}
		},
		stats={
			[1]="display_nearby_enemies_are_taunted"
		}
	},
	[96]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Enable Explosive Teleport",
				text="DNT-UNUSED Enable Explosive Teleport"
			}
		},
		stats={
			[1]="display_sand_djinn_enable_explode_teleport"
		}
	},
	[97]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Enable Hand Slam",
				text="DNT-UNUSED Enable Hand Slam"
			}
		},
		stats={
			[1]="display_sand_djinn_enable_hand_slam"
		}
	},
	[98]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] Enable Knife Toss",
				text="DNT-UNUSED Enable Knife Toss"
			}
		},
		stats={
			[1]="display_sand_djinn_enable_knife_throw"
		}
	},
	[99]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Attribute Passive Skills can instead grant 5% increased Damage\nAttribute Passive Skills can instead grant 5% increased [Armour], [Evasion] and [EnergyShield|Energy Shield]\nAttribute Passive Skills can instead grant 5% increased Cost [Efficiency]",
				text="Attribute Passive Skills can instead grant 5% increased Damage\nAttribute Passive Skills can instead grant 5% increased Armour, Evasion and Energy Shield\nAttribute Passive Skills can instead grant 5% increased Cost Efficiency"
			}
		},
		stats={
			[1]="display_travellers_wisdom_extra_attribute_options"
		}
	},
	[100]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="You have {0} Fortification",
				text="You have {0} Fortification"
			}
		},
		stats={
			[1]="display_you_have_x_fortification"
		}
	},
	[101]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more [ESRecharge|Energy Shield Recharge Rate] while on [LowEnergyShield|Low Energy Shield]",
				text="{0}% more Energy Shield Recharge Rate while on Low Energy Shield"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less [ESRecharge|Energy Shield Recharge Rate] while on [LowEnergyShield|Low Energy Shield]",
				text="{0}% less Energy Shield Recharge Rate while on Low Energy Shield"
			}
		},
		stats={
			[1]="djinn_ascendancy_energy_shield_recharge_rate_+%_final_on_low_energy_shield"
		}
	},
	[102]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Double [Adaptation] Effect",
				text="Double Adaptation Effect"
			}
		},
		stats={
			[1]="double_adaptation_effect"
		}
	},
	[103]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0}% of [ElementalDamage|Elemental Damage] is taken from Mana before Life",
				text="{0}% of Elemental Damage is taken from Mana before Life"
			}
		},
		stats={
			[1]="elemental_damage_removed_from_mana_before_life_%"
		}
	},
	[104]={
		[1]={
			[1]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less Damage taken of each [ElementalDamage|Elemental Damage Type] per matching [Adaptation]",
				text="{0}% less Damage taken of each Elemental Damage Type per matching Adaptation"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more Damage taken of each [ElementalDamage|Elemental Damage Type] per matching [Adaptation]",
				text="{0}% more Damage taken of each Elemental Damage Type per matching Adaptation"
			}
		},
		stats={
			[1]="ascendancy_druid_shaman_elemental_damage_taken_+%_final_per_matching_adaptation"
		}
	},
	[105]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0:+d} to [Limit] for [ElementalDamage|Elemental] Skills",
				text="{0:+d} to Limit for Elemental Skills"
			}
		},
		stats={
			[1]="elemental_skill_limit_+"
		}
	},
	[106]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Every second, inflict Withered on nearby Enemies for {0} seconds",
				text="Every second, inflict Withered on nearby Enemies for {0} seconds"
			}
		},
		stats={
			[1]="every_1_second_nearby_enemies_withered_for_X_ms"
		}
	},
	[107]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased bonuses gained from Equipped [Focus]",
				text="{0}% increased bonuses gained from Equipped Focus"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced bonuses gained from Equipped [Focus]",
				text="{0}% reduced bonuses gained from Equipped Focus"
			}
		},
		stats={
			[1]="focus_mod_effect_+%"
		}
	},
	[108]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Gain {0} [Volatility] on inflicting an [ElementalAilments|Elemental Ailment]",
				text="Gain {0} Volatility on inflicting an Elemental Ailment"
			}
		},
		stats={
			[1]="gain_X_volatility_on_inflicting_elemental_ailment"
		}
	},
	[109]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[HitDamage|Hit] damage is taken from Mana before Life if your current Mana is higher than your current Life",
				text="Hit damage is taken from Mana before Life if your current Mana is higher than your current Life"
			}
		},
		stats={
			[1]="hit_damage_remove_from_mana_before_life_while_mana_higher_than_life"
		}
	},
	[110]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Take no Damage from [Volatility]",
				text="Take no Damage from Volatility"
			}
		},
		stats={
			[1]="immune_to_volatility_damage"
		}
	},
	[111]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain [ElementalArchon|Elemental Archon] when you cast a [Spell] while on [HighInfernalFlame|High Infernal Flame]",
				text="Gain Elemental Archon when you cast a Spell while on High Infernal Flame"
			}
		},
		stats={
			[1]="gain_elemental_archon_when_you_cast_a_spell_while_on_high_infernal_flame"
		}
	},
	[112]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[ElementalArchon|Elemental Archon] does not expire while on [HighInfernalFlame|High Infernal Flame]",
				text="Elemental Archon does not expire while on High Infernal Flame"
			}
		},
		stats={
			[1]="elemental_archon_does_not_expire_while_on_high_infernal_flame"
		}
	},
	[113]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Lose [ElementalArchon|Elemental Archon] on reaching maximum Infernal Flame",
				text="Lose Elemental Archon on reaching maximum Infernal Flame"
			}
		},
		stats={
			[1]="lose_elemental_archone_on_reaching_full_infernal_flame"
		}
	},
	[114]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can have two [Companion|Companions] of different types\n30% more [Reservation] [Efficiency] of [Companion] Skills\n20% less [Reservation] [Efficiency] of non-[Companion] Skills",
				text="You can have two Companions of different types\n30% more Reservation Efficiency of Companion Skills\n20% less Reservation Efficiency of non-Companion Skills"
			}
		},
		stats={
			[1]="keystone_2_companions"
		}
	},
	[115]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Dodge Roll cannot Avoid Damage\nTake 30% less [HitDamage|Damage from Hits] while Dodge Rolling",
				text="Dodge Roll cannot Avoid Damage\nTake 30% less Damage from Hits while Dodge Rolling"
			}
		},
		stats={
			[1]="keystone_bulwark"
		}
	},
	[116]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Bleeding] you inflict is [Aggravate|Aggravated]\nBase [Bleeding] Duration is 1 second\n50% more [BuffMagnitude|Magnitude] of [Bleeding] you inflict",
				text="Bleeding you inflict is Aggravated\nBase Bleeding Duration is 1 second\n50% more Magnitude of Bleeding you inflict"
			}
		},
		stats={
			[1]="keystone_crimson_assault"
		}
	},
	[117]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can inflict Bleeding on an Enemy up to 8 times\nYour Bleeding does not deal extra Damage while the Enemy is moving\n50% less Damage with Bleeding",
				text="You can inflict Bleeding on an Enemy up to 8 times\nYour Bleeding does not deal extra Damage while the Enemy is moving\n50% less Damage with Bleeding"
			}
		},
		stats={
			[1]="keystone_crimson_dance"
		}
	},
	[118]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="25% more Skill Speed while Off Hand is empty and you have\na [One-Handed] [MartialWeapon|Martial Weapon] equipped in your Main Hand",
				text="25% more Skill Speed while Off Hand is empty and you have\na One-Handed Martial Weapon equipped in your Main Hand"
			}
		},
		stats={
			[1]="keystone_dance_with_death"
		}
	},
	[119]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can wield [Two-Handed] [Axe|Axes], [Mace|Maces] and [Sword|Swords] in one hand\nTriple [Attributes|Attribute] requirements of [MartialWeapon|Martial Weapons]\nInherent Life granted by [Strength] is halved",
				text="You can wield Two-Handed Axes, Maces and Swords in one hand\nTriple Attribute requirements of Martial Weapons\nInherent Life granted by Strength is halved"
			}
		},
		stats={
			[1]="keystone_giants_blood"
		}
	},
	[120]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Excess Life Recovery from Regeneration is applied to [EnergyShield|Energy Shield]\n[EnergyShield|Energy Shield] does not Recharge",
				text="Excess Life Recovery from Regeneration is applied to Energy Shield\nEnergy Shield does not Recharge"
			}
		},
		stats={
			[1]="keystone_zealots_oath"
		}
	},
	[121]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Leech] recovers based on [Chaos] Damage as well as [Physical] Damage",
				text="Leech recovers based on Chaos Damage as well as Physical Damage"
			}
		},
		stats={
			[1]="leech_also_recovers_based_on_chaos_damage_as_well"
		}
	},
	[122]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Life [LifeLeech|Leeched] from [Empowered] Attacks is Instant",
				text="Life Leeched from Empowered Attacks is Instant"
			}
		},
		stats={
			[1]="life_leech_is_instant_for_empowered_attacks"
		}
	},
	[123]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Nearby Enemies have {0}% increased Life Regeneration Rate",
				text="Nearby Enemies have {0}% increased Life Regeneration Rate"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="Nearby Enemies have {0}% reduced Life Regeneration Rate",
				text="Nearby Enemies have {0}% reduced Life Regeneration Rate"
			}
		},
		stats={
			[1]="life_mastery_nearby_enemy_life_regeneration_rate_+%"
		}
	},
	[124]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Increases and Reductions to Mana Regeneration Rate also apply to [Rage] Regeneration Rate",
				text="Increases and Reductions to Mana Regeneration Rate also apply to Rage Regeneration Rate"
			}
		},
		stats={
			[1]="mana_regeneration_rate_modifiers_apply_to_rage_regeneration"
		}
	},
	[125]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Maximum [Block] chance is {0}%",
				text="Maximum Block chance is {0}%"
			}
		},
		stats={
			[1]="maximum_block_chance_override"
		}
	},
	[126]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased maximum Darkness per 1% [Chaos|Chaos Resistance]",
				text="{0}% increased maximum Darkness per 1% Chaos Resistance"
			}
		},
		stats={
			[1]="maximum_darkness_+%_per_capped_chaos_damage_resistance"
		}
	},
	[127]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] {0:+d} to maximum Mana per fifty [ItemEvasion|Item Evasion] on [EquipArmour|Equipped Armour Items]",
				text="DNT-UNUSED {0:+d} to maximum Mana per fifty Item Evasion on Equipped Armour Items"
			}
		},
		stats={
			[1]="maximum_mana_per_50_evasion_rating_from_armour_items"
		}
	},
	[128]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Minion|Minions] [Gain] {0}% of Elemental Damage as Extra Chaos Damage",
				text="Minions Gain {0}% of Elemental Damage as Extra Chaos Damage"
			}
		},
		stats={
			[1]="minion_non_skill_base_elemental_damage_%_to_gain_as_chaos"
		}
	},
	[129]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased Movement Speed Penalty while Actively [Block|Blocking]",
				text="{0}% increased Movement Speed Penalty while Actively Blocking"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced Movement Speed Penalty while Actively [Block|Blocking]",
				text="{0}% reduced Movement Speed Penalty while Actively Blocking"
			}
		},
		stats={
			[1]="movement_speed_penalty_+%_while_raising_shield"
		}
	},
	[130]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Attack|Attacks] [Empowered] by Owl Feathers have {0}% more [CriticalDamageBonus|Critical Damage Bonus]",
				text="Attacks Empowered by Owl Feathers have {0}% more Critical Damage Bonus"
			}
		},
		stats={
			[1]="multishot_critical_damage_bonus_+%_final"
		}
	},
	[131]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Skills have {0:+d} to [Rage] cost",
				text="Skills have {0:+d} to Rage cost"
			}
		},
		stats={
			[1]="natures_sustenance_added_rage_cost"
		}
	},
	[132]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="{0:+d} to Maximum [Rage]",
				text="{0:+d} to Maximum Rage"
			}
		},
		stats={
			[1]="natures_sustenance_additional_maximum_rage"
		}
	},
	[133]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Projectile Barrages have no spread",
				text="Projectile Barrages have no spread"
			}
		},
		stats={
			[1]="no_barrage_projectile_spread"
		}
	},
	[134]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					},
					[3]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="For each colour of Socketed Support Gem that is most numerous, gain:\n•Red: [HitDamage|Hits] against you have no [CriticalDamageBonus|Critical Damage Bonus]\n•Blue: Skills have {1}% more cost\n•Green: {2}% more Movement Speed Penalty from using Skills while Moving",
				text="For each colour of Socketed Support Gem that is most numerous, gain:\nRed: Hits against you have no Critical Damage Bonus\nBlue: Skills have {1}% more cost\nGreen: {2}% more Movement Speed Penalty from using Skills while Moving"
			},
			[2]={
				[1]={
					k="negate",
					v=2
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]=-1
					},
					[3]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="For each colour of Socketed Support Gem that is most numerous, gain:\n•Red: [HitDamage|Hits] against you have no [CriticalDamageBonus|Critical Damage Bonus]\n•Blue: Skills have {1}% less cost\n•Green: {2}% more Movement Speed Penalty from using Skills while Moving",
				text="For each colour of Socketed Support Gem that is most numerous, gain:\nRed: Hits against you have no Critical Damage Bonus\nBlue: Skills have {1}% less cost\nGreen: {2}% more Movement Speed Penalty from using Skills while Moving"
			},
			[3]={
				[1]={
					k="negate",
					v=2
				},
				[2]={
					k="negate",
					v=3
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]="#",
						[2]=-1
					},
					[3]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="For each colour of Socketed Support Gem that is most numerous, gain:\n•Red: [HitDamage|Hits] against you have no [CriticalDamageBonus|Critical Damage Bonus]\n•Blue: Skills have {1}% less cost\n•Green: {2}% less Movement Speed Penalty from using Skills while Moving",
				text="For each colour of Socketed Support Gem that is most numerous, gain:\nRed: Hits against you have no Critical Damage Bonus\nBlue: Skills have {1}% less cost\nGreen: {2}% less Movement Speed Penalty from using Skills while Moving"
			},
			[4]={
				[1]={
					k="negate",
					v=3
				},
				limit={
					[1]={
						[1]=1,
						[2]="#"
					},
					[2]={
						[1]=1,
						[2]="#"
					},
					[3]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="For each colour of Socketed Support Gem that is most numerous, gain:\n•Red: [HitDamage|Hits] against you have no [CriticalDamageBonus|Critical Damage Bonus]\n•Blue: Skills have {1}% more cost\n•Green: {2}% less Movement Speed Penalty from using Skills while Moving",
				text="For each colour of Socketed Support Gem that is most numerous, gain:\nRed: Hits against you have no Critical Damage Bonus\nBlue: Skills have {1}% more cost\nGreen: {2}% less Movement Speed Penalty from using Skills while Moving"
			}
		},
		stats={
			[1]="no_self_critical_strike_multiplier_if_red_support_count_highest",
			[2]="skill_cost_+%_final_if_blue_support_count_highest",
			[3]="movement_speed_penalty_+%_final_while_performing_action_if_green_support_count_highest"
		}
	},
	[135]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Non-[Rarity|Unique] Time-Lost [Jewel|Jewels] have {0}% increased radius",
				text="Non-Unique Time-Lost Jewels have {0}% increased radius"
			}
		},
		stats={
			[1]="ascendancy_non_unique_jewel_radius_+%"
		}
	},
	[136]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Your [Offering|Offerings] can target Enemies in [CullingStrike|Culling] range",
				text="Your Offerings can target Enemies in Culling range"
			}
		},
		stats={
			[1]="offering_skill_target_cullable_enemies_instead"
		}
	},
	[137]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Your [Offering|Offerings] affect you instead of your [Minion|Minions]",
				text="Your Offerings affect you instead of your Minions"
			}
		},
		stats={
			[1]="offerings_only_buff_you"
		}
	},
	[138]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[InevitableCriticalHits|Inevitable Critical Hits]",
				text="Inevitable Critical Hits"
			}
		},
		stats={
			[1]="oracle_hits_eventually_crit_with_critical_strike_multiplier_+%_final_per_failed_roll"
		}
	},
	[139]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more maximum Life",
				text="{0}% more maximum Life"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less maximum Life",
				text="{0}% less maximum Life"
			}
		},
		stats={
			[1]="oracle_maximum_life_+%_final"
		}
	},
	[140]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% more maximum Mana",
				text="{0}% more maximum Mana"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% less maximum Mana",
				text="{0}% less maximum Mana"
			}
		},
		stats={
			[1]="oracle_maximum_mana_+%_final"
		}
	},
	[141]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [Physical] Damage",
				text="{0}% increased Physical Damage"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [Physical] Damage",
				text="{0}% reduced Physical Damage"
			}
		},
		stats={
			[1]="physical_damage_+%"
		}
	},
	[142]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Physical] [Spell] [Critical] [HitDamage|Hits] build [Pinned|Pin]",
				text="Physical Spell Critical Hits build Pin"
			}
		},
		stats={
			[1]="physical_spell_damage_can_pin_on_critical_hit"
		}
	},
	[143]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Pinned] Enemies cannot deal [Critical|Critical Hits]",
				text="Pinned Enemies cannot deal Critical Hits"
			}
		},
		stats={
			[1]="pinned_enemies_cannot_crit"
		}
	},
	[144]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Your Hits cannot be [Evasion|Evaded] by [Pinned] Enemies",
				text="Your Hits cannot be Evaded by Pinned Enemies"
			}
		},
		stats={
			[1]="pinned_enemies_cannot_evade_your_attacks"
		}
	},
	[145]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] [Projectile] [Attack|Attacks] always [Chain] to [Mark|Marked] Enemies with {0}% increased [Chain|Chaining Distance]",
				text="DNT-UNUSED Projectile Attacks always Chain to Marked Enemies with {0}% increased Chaining Distance"
			}
		},
		stats={
			[1]="projectile_attacks_always_chain_to_marked_enemies_with_%_increased_chaining_distance"
		}
	},
	[146]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain {0} [Rage] when you use a Life [Flask]",
				text="Gain {0} Rage when you use a Life Flask"
			}
		},
		stats={
			[1]="rage_gained_on_life_flask_use"
		}
	},
	[147]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[DNT-UNUSED] [Freeze] you inflict has up to {0}% increased duration, at random",
				text="DNT-UNUSED Freeze you inflict has up to {0}% increased duration, at random"
			}
		},
		stats={
			[1]="random_freeze_duration_+%_up_to_%"
		}
	},
	[148]={
		[1]={
			[1]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]=1000,
						[2]=1000
					}
				},
				rawText="[Remnant|Remnants] you create reappear once, {0} second after being collected",
				text="Remnants you create reappear once, {0} second after being collected"
			},
			[2]={
				[1]={
					k="milliseconds_to_seconds_2dp_if_required",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Remnant|Remnants] you create reappear once, {0} seconds after being collected",
				text="Remnants you create reappear once, {0} seconds after being collected"
			}
		},
		stats={
			[1]="remnants_you_create_reappear_X_ms_after_being_collected"
		}
	},
	[149]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Sacrifice|Sacrificing] [EnergyShield|Energy Shield] does not interrupt [ESRecharge|Recharge]",
				text="Sacrificing Energy Shield does not interrupt Recharge"
			}
		},
		stats={
			[1]="sacrificing_energy_shield_does_not_interrupt_recharge"
		}
	},
	[150]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased [BuffMagnitude|Magnitude] of [Shock|Shock] you inflict",
				text="{0}% increased Magnitude of Shock you inflict"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced [BuffMagnitude|Magnitude] of [Shock|Shock] you inflict",
				text="{0}% reduced Magnitude of Shock you inflict"
			}
		},
		stats={
			[1]="shock_effect_+%"
		}
	},
	[151]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0}% increased cost of Skills per [SoulCore|Soul Core] in your equipment",
				text="{0}% increased cost of Skills per Soul Core in your equipment"
			},
			[2]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="{0}% reduced cost of Skills per [SoulCore|Soul Core] in your equipment",
				text="{0}% reduced cost of Skills per Soul Core in your equipment"
			}
		},
		stats={
			[1]="skill_cost_+%_per_socketed_soul_core"
		}
	},
	[152]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="!",
						[2]=0
					},
					[2]={
						[1]=0,
						[2]=0
					}
				},
				rawText="[Sacrifice] {0}% of maximum [EnergyShield|Energy Shield] when you Cast a [Spell]",
				text="Sacrifice {0}% of maximum Energy Shield when you Cast a Spell"
			},
			[2]={
				limit={
					[1]={
						[1]="!",
						[2]=0
					},
					[2]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Sacrifice] {0}% of maximum [EnergyShield|Energy Shield] when you Cast a [Spell]\n[Spell|Spells] for which this [Sacrifice] was fully made deal {1}% more Damage",
				text="Sacrifice {0}% of maximum Energy Shield when you Cast a Spell\nSpells for which this Sacrifice was fully made deal {1}% more Damage"
			},
			[3]={
				[1]={
					k="negate",
					v=1
				},
				limit={
					[1]={
						[1]="!",
						[2]=0
					},
					[2]={
						[1]="#",
						[2]=-1
					}
				},
				rawText="[Sacrifice] {0}% of maximum [EnergyShield|Energy Shield] when you Cast a [Spell]\n[Spell|Spells] for which this [Sacrifice] was fully made deal {1}% less Damage",
				text="Sacrifice {0}% of maximum Energy Shield when you Cast a Spell\nSpells for which this Sacrifice was fully made deal {1}% less Damage"
			}
		},
		stats={
			[1]="spells_sacrifice_%_of_your_energy_shield",
			[2]="ascendancy_lich_spell_damage_+%_final_when_sacrificing_energy_shield"
		}
	},
	[153]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Your [EnergyShield|Energy Shield] starts at zero",
				text="Your Energy Shield starts at zero"
			}
		},
		stats={
			[1]="start_at_zero_energy_shield"
		}
	},
	[154]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Totem|Totems] you place grant [TacticianTotemBuff|Embankment Auras]",
				text="Totems you place grant Embankment Auras"
			}
		},
		stats={
			[1]="tactician_grants_aura_to_deployed_totems"
		}
	},
	[155]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="There is no [Limit] on the number of [Banner|Banners] you can place",
				text="There is no Limit on the number of Banners you can place"
			}
		},
		stats={
			[1]="unlimited_banners_allowed"
		}
	},
	[156]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="Grants [UnravellingBuff|Unravelling]",
				text="Grants Unravelling"
			}
		},
		stats={
			[1]="unravelling_cycling_buff_every_x_ms"
		}
	},
	[157]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Companion|Companions] gain added [Attack] damage equal to {0}% of your main hand Weapon's damage",
				text="Companions gain added Attack damage equal to {0}% of your main hand Weapon's damage"
			}
		},
		stats={
			[1]="weapon_damage_%_granted_to_companions"
		}
	},
	[158]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Phasing",
				text="Phasing"
			}
		},
		stats={
			[1]="base_phasing_without_visual"
		}
	},
	[159]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="[Offering|Offerings] created by [CullingStrike|Culling] Enemies have {0}% increased [BuffEffect|Effect] per [Power] of [CullingStrike|Culled] Enemy",
				text="Offerings created by Culling Enemies have {0}% increased Effect per Power of Culled Enemy"
			}
		},
		stats={
			[1]="lich_offering_effect_+%_per_enemy_power"
		}
	},
	[160]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]=-1,
						[2]=-1
					}
				},
				rawText="No path found to your Class' starting location",
				text="No path found to your Class' starting location"
			},
			[2]={
				limit={
					[1]={
						[1]=1,
						[2]="#"
					}
				},
				rawText="{0} Allocated Passive Skills between this Socket and your Class' starting location",
				text="{0} Allocated Passive Skills between this Socket and your Class' starting location"
			}
		},
		stats={
			[1]="local_jewel_display_number_of_allocated_passives_between_jewel_and_class_start"
		}
	},
	[161]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain no inherent bonus from [Dexterity]\n1% increased [Armour|Armour] per 2 Dexterity",
				text="Gain no inherent bonus from Dexterity\n1% increased Armour per 2 Dexterity"
			}
		},
		stats={
			[1]="keystone_alternate_dexterity_bonus"
		}
	},
	[162]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="5% of [Physical] Damage prevented [Recoup|Recouped] as [EnergyShield|Energy Shield] per enemy [Power]\n[EnergyShield|Energy Shield] does not [ESRecharge|Recharge]\nYou cannot Recover [EnergyShield|Energy Shield] from Regeneration\nYou cannot Recover [EnergyShield|Energy Shield] to above [Armour]",
				text="5% of Physical Damage prevented Recouped as Energy Shield per enemy Power\nEnergy Shield does not Recharge\nYou cannot Recover Energy Shield from Regeneration\nYou cannot Recover Energy Shield to above Armour"
			}
		},
		stats={
			[1]="keystone_alternate_es_recovery"
		}
	},
	[163]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain no inherent bonus from [Intelligence]\n1% increased [Evasion|Evasion Rating] per 2 Intelligence",
				text="Gain no inherent bonus from Intelligence\n1% increased Evasion Rating per 2 Intelligence"
			}
		},
		stats={
			[1]="keystone_alternate_intelligence_bonus"
		}
	},
	[164]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain no inherent bonus from [Strength]\n1% increased [EnergyShield|Energy Shield] per 2 Strength",
				text="Gain no inherent bonus from Strength\n1% increased Energy Shield per 2 Strength"
			}
		},
		stats={
			[1]="keystone_alternate_strength_bonus"
		}
	},
	[165]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="When taking damage from [HitDamage|Hits], 20% of Life Loss is prevented, then 150% of Life Loss prevented this way is Lost over 4 seconds",
				text="When taking damage from Hits, 20% of Life Loss is prevented, then 150% of Life Loss prevented this way is Lost over 4 seconds"
			}
		},
		stats={
			[1]="keystone_amanamus_defiance"
		}
	},
	[166]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Invoke|Invocation] Skills instead [Trigger] [Spell|Spells] every 2 seconds\n[Invoke|Invocation] Skills cannot gain [Energy] while [Trigger|Triggering] [Spell|Spells]\n[Invoke|Invoked] Spells consume 50% less [Energy]",
				text="Invocation Skills instead Trigger Spells every 2 seconds\nInvocation Skills cannot gain Energy while Triggering Spells\nInvoked Spells consume 50% less Energy"
			}
		},
		stats={
			[1]="keystone_auto_invocation"
		}
	},
	[167]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Attack] Projectiles always inflict Bleeding and Maim, and Knock Back Enemies\nProjectiles cannot Pierce, Fork or Chain",
				text="Attack Projectiles always inflict Bleeding and Maim, and Knock Back Enemies\nProjectiles cannot Pierce, Fork or Chain"
			}
		},
		stats={
			[1]="keystone_barbed_tips"
		}
	},
	[168]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You are Blind\nBlind does not affect your Light Radius\n25% more [Melee] [Critical|Critical Hit] Chance while Blinded",
				text="You are Blind\nBlind does not affect your Light Radius\n25% more Melee Critical Hit Chance while Blinded"
			}
		},
		stats={
			[1]="keystone_blind_monk"
		}
	},
	[169]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Using Warcries is Instant\nWarcries share their Cooldown",
				text="Using Warcries is Instant\nWarcries share their Cooldown"
			}
		},
		stats={
			[1]="keystone_call_to_arms"
		}
	},
	[170]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain [Charges|Power Charges] instead of [Charges|Frenzy Charges]\nGain [Charges|Frenzy Charges] instead of [Charges|Endurance Charges]\nGain [Charges|Endurance Charges] instead of [Charges|Power Charges]",
				text="Gain Power Charges instead of Frenzy Charges\nGain Frenzy Charges instead of Endurance Charges\nGain Endurance Charges instead of Power Charges"
			}
		},
		stats={
			[1]="keystone_charge_cycle"
		}
	},
	[171]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Every second, Consume a nearby Corpse to Recover 5% of maximum Life and Mana\n10% more Damage taken if you haven't Consumed a Corpse [Recently]",
				text="Every second, Consume a nearby Corpse to Recover 5% of maximum Life and Mana\n10% more Damage taken if you haven't Consumed a Corpse Recently"
			}
		},
		stats={
			[1]="keystone_disciple_of_kitava"
		}
	},
	[172]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="All Damage taken bypasses Energy Shield\n50% of Elemental Damage taken as Chaos Damage\n+5% to maximum Chaos Resistance",
				text="All Damage taken bypasses Energy Shield\n50% of Elemental Damage taken as Chaos Damage\n+5% to maximum Chaos Resistance"
			}
		},
		stats={
			[1]="keystone_divine_flesh"
		}
	},
	[173]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Cannot Recover [EnergyShield|Energy Shield] to above Armour\n3% of Physical Damage prevented from Hits Recently is Regenerated as [EnergyShield|Energy Shield] per second",
				text="Cannot Recover Energy Shield to above Armour\n3% of Physical Damage prevented from Hits Recently is Regenerated as Energy Shield per second"
			}
		},
		stats={
			[1]="keystone_divine_shield"
		}
	},
	[174]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="100% more Maximum [Rage]\nRegenerate 1 [Rage] per second per 4 [Rage] spent [Recently]\nNo [Rage] effect",
				text="100% more Maximum Rage\nRegenerate 1 Rage per second per 4 Rage spent Recently\nNo Rage effect"
			}
		},
		stats={
			[1]="keystone_druidic_rage"
		}
	},
	[175]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Skills that have dealt a [Critical|Critical Hit] in the past 8 seconds deal 40% more Elemental Damage with Hits\nYour [Critical|Critical Hits] do not deal extra Damage",
				text="Skills that have dealt a Critical Hit in the past 8 seconds deal 40% more Elemental Damage with Hits\nYour Critical Hits do not deal extra Damage"
			}
		},
		stats={
			[1]="keystone_elemental_overload"
		}
	},
	[176]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Life Recovery from [Flask|Flasks] also applies to Energy Shield\n30% less Life Recovery from [Flask|Flasks]",
				text="Life Recovery from Flasks also applies to Energy Shield\n30% less Life Recovery from Flasks"
			}
		},
		stats={
			[1]="keystone_emperors_heart"
		}
	},
	[177]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Life [LifeRecharge|Recharges] instead of [ESRecharge|Energy Shield]\n50% less Life Recovery from [Flask|Flasks]",
				text="Life Recharges instead of Energy Shield\n50% less Life Recovery from Flasks"
			}
		},
		stats={
			[1]="keystone_eternal_youth"
		}
	},
	[178]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Fire] [Spell|Spells] [Conversion|Convert] 100% of Fire Damage to [Chaos|Chaos Damage]\n[Chaos|Chaos Damage] from [Fire] [Spell|Spells] [Contributes] to [Flammability] and [Ignite] [BuffMagnitude|Magnitudes]\n[Ignite] inflicted with [Fire] [Spell|Spells] deals [Chaos|Chaos Damage] instead of Fire Damage",
				text="Fire Spells Convert 100% of Fire Damage to Chaos Damage\nChaos Damage from Fire Spells Contributes to Flammability and Ignite Magnitudes\nIgnite inflicted with Fire Spells deals Chaos Damage instead of Fire Damage"
			}
		},
		stats={
			[1]="keystone_fire_spells_become_chaos_spells"
		}
	},
	[179]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Mana Recovery from Regeneration is not applied\n1 Rage Regenerated for every 25 Mana Regeneration per Second\nSkills Cost +3 Rage",
				text="Mana Recovery from Regeneration is not applied\n1 Rage Regenerated for every 25 Mana Regeneration per Second\nSkills Cost +3 Rage"
			}
		},
		stats={
			[1]="keystone_focused_rage"
		}
	},
	[180]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Chance to [Evasion|Evade] is [Unlucky]\nChance to [Deflect] is [Lucky]",
				text="Chance to Evade is Unlucky\nChance to Deflect is Lucky"
			}
		},
		stats={
			[1]="keystone_glancing_blows"
		}
	},
	[181]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Take 50% less Damage over Time if you've started taking Damage over Time in the past second\nTake 50% more Damage over Time if you haven't started taking Damage over Time in the past second",
				text="Take 50% less Damage over Time if you've started taking Damage over Time in the past second\nTake 50% more Damage over Time if you haven't started taking Damage over Time in the past second"
			}
		},
		stats={
			[1]="keystone_heartstopper"
		}
	},
	[182]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can only have one Herald\n50% more Effect of Herald Buffs on you\n100% more Damage with Hits from Herald Skills\n50% more Damage Over Time with Herald Skills\nMinions from Herald Skills deal 25% more Damage\nYour Aura Skills are Disabled",
				text="You can only have one Herald\n50% more Effect of Herald Buffs on you\n100% more Damage with Hits from Herald Skills\n50% more Damage Over Time with Herald Skills\nMinions from Herald Skills deal 25% more Damage\nYour Aura Skills are Disabled"
			}
		},
		stats={
			[1]="keystone_herald_of_doom"
		}
	},
	[183]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can apply an additional [Curse]\nDouble Activation Delay of [Curse|Curses]",
				text="You can apply an additional Curse\nDouble Activation Delay of Curses"
			}
		},
		stats={
			[1]="keystone_hex_master"
		}
	},
	[184]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Can [Attack] as though using a [Quarterstaff] while both of your hand slots are empty\n[UnarmedAttack|Unarmed Attacks] that would use an [Equipped] [Quarterstaff]'s damage have:\n• Base [UnarmedDamage|Unarmed] [Physical] damage replaced with damage based on their Skill Level\n• 1% more [Attack] Speed per 75 [ItemEvasion|Item Evasion] on [EquipArmour|Equipped Armour Items]\n• +0.1% to [Critical|Critical Hit Chance] per 10 [ItemEnergyShield|Item Energy Shield] on [EquipArmour|Equipped Armour Items]",
				text="Can Attack as though using a Quarterstaff while both of your hand slots are empty\nUnarmed Attacks that would use an Equipped Quarterstaff's damage have:\nBase Unarmed Physical damage replaced with damage based on their Skill Level\n1% more Attack Speed per 75 Item Evasion on Equipped Armour Items\n+0.1% to Critical Hit Chance per 10 Item Energy Shield on Equipped Armour Items"
			}
		},
		stats={
			[1]="keystone_hollow_palm_technique"
		}
	},
	[185]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="When your Hits Impale Enemies, also Impale other Enemies near them\nInflict 4 additional Impales on Enemies you Impale\nFor 4 seconds after you Impale Enemies, they cannot be Impaled again, and Impales cannot be Called from them",
				text="When your Hits Impale Enemies, also Impale other Enemies near them\nInflict 4 additional Impales on Enemies you Impale\nFor 4 seconds after you Impale Enemies, they cannot be Impaled again, and Impales cannot be Called from them"
			}
		},
		stats={
			[1]="keystone_impale"
		}
	},
	[186]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain no inherent bonus from [Strength]\n1% increased [Projectile] [Attack] damage per 2 [Strength]",
				text="Gain no inherent bonus from Strength\n1% increased Projectile Attack damage per 2 Strength"
			}
		},
		stats={
			[1]="keystone_iron_grip"
		}
	},
	[187]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain no inherent bonus from [Strength]\n1% increased [Spell] damage per 2 [Strength]",
				text="Gain no inherent bonus from Strength\n1% increased Spell damage per 2 Strength"
			}
		},
		stats={
			[1]="keystone_iron_will"
		}
	},
	[188]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You deal 1% more Damage per 2 total [Power|Power] of your Undead Minions\nUndead Minions have 25% less maximum Life",
				text="You deal 1% more Damage per 2 total Power of your Undead Minions\nUndead Minions have 25% less maximum Life"
			}
		},
		stats={
			[1]="keystone_kulemaks_sovereignty"
		}
	},
	[189]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Mana Recovery from Regeneration [Overflow|Overflows] maximum Mana\n50% less Mana Regeneration Rate",
				text="Mana Recovery from Regeneration Overflows maximum Mana\n50% less Mana Regeneration Rate"
			}
		},
		stats={
			[1]="keystone_kurgals_ambition"
		}
	},
	[190]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="You can equip a non-[ItemRarity|Unique] [Sceptre] while wielding a [Talisman]\n50% less [Spirit]\nNon-[Minion] Skills have 50% less [Reservation] [Efficiency]",
				text="You can equip a non-Unique Sceptre while wielding a Talisman\n50% less Spirit\nNon-Minion Skills have 50% less Reservation Efficiency"
			}
		},
		stats={
			[1]="keystone_lord_of_the_wilds"
		}
	},
	[191]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Nearby Allies and Enemies Share Charges with you\nEnemies Hitting you have 10% chance to gain an Endurance, \nFrenzy or Power Charge",
				text="Nearby Allies and Enemies Share Charges with you\nEnemies Hitting you have 10% chance to gain an Endurance, \nFrenzy or Power Charge"
			}
		},
		stats={
			[1]="keystone_magnetic_charge"
		}
	},
	[192]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="80% of Maximum Mana is Converted to twice that much [Armour]",
				text="80% of Maximum Mana is Converted to twice that much Armour"
			}
		},
		stats={
			[1]="keystone_mental_conditioning"
		}
	},
	[193]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Gain 2 Grasping Vines each second while stationary\n2% chance to deal Double Damage per Grasping Vine\n1% less Damage taken per Grasping Vine",
				text="Gain 2 Grasping Vines each second while stationary\n2% chance to deal Double Damage per Grasping Vine\n1% less Damage taken per Grasping Vine"
			}
		},
		stats={
			[1]="keystone_natures_presence"
		}
	},
	[194]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Cannot use [Charm|Charms]\n30% more Recovery from [Flask|Flasks]",
				text="Cannot use Charms\n30% more Recovery from Flasks"
			}
		},
		stats={
			[1]="keystone_oasis"
		}
	},
	[195]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="40% more [Attack] Damage if Accuracy Rating is higher than Maximum Life\nNever deal [Critical|Critical Hits]",
				text="40% more Attack Damage if Accuracy Rating is higher than Maximum Life\nNever deal Critical Hits"
			}
		},
		stats={
			[1]="keystone_precise_technique"
		}
	},
	[196]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="+100% of [Armour] applies to [ElementalDamage|Elemental Damage]\n[Armour] does not apply to [Physical|Physical Damage]\n-15% to all maximum Elemental Resistances",
				text="+100% of Armour applies to Elemental Damage\nArmour does not apply to Physical Damage\n-15% to all maximum Elemental Resistances"
			}
		},
		stats={
			[1]="keystone_prismatic_bulwark"
		}
	},
	[197]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="3% more [Spell|Spell] Damage per [Charges|Power Charge]\nGain [Charges|Power Charges] instead of [Charges|Frenzy Charges]",
				text="3% more Spell Damage per Power Charge\nGain Power Charges instead of Frenzy Charges"
			}
		},
		stats={
			[1]="keystone_quiet_might"
		}
	},
	[198]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="-1 to maximum number of Summoned Totems\nYou can have an additional Brand Attached to an Enemy",
				text="-1 to maximum number of Summoned Totems\nYou can have an additional Brand Attached to an Enemy"
			}
		},
		stats={
			[1]="keystone_runebinder"
		}
	},
	[199]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="100% chance to Defend with 200% of Armour\nMaximum Damage Reduction for any Damage Type is 50%",
				text="100% chance to Defend with 200% of Armour\nMaximum Damage Reduction for any Damage Type is 50%"
			}
		},
		stats={
			[1]="keystone_sacred_bastion"
		}
	},
	[200]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Cannot Ignite, Chill, Freeze or Shock\n[Critical|Critical Hits] inflict Scorch, Brittle and Sapped",
				text="Cannot Ignite, Chill, Freeze or Shock\nCritical Hits inflict Scorch, Brittle and Sapped"
			}
		},
		stats={
			[1]="keystone_secrets_of_suffering"
		}
	},
	[201]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Can't use Helmets\nYour [Critical|Critical Hit] Chance is Lucky\nYour Damage with [Critical|Critical Hits] is Lucky\nEnemies' Damage with [Critical|Critical Hits] against you is Lucky",
				text="Can't use Helmets\nYour Critical Hit Chance is Lucky\nYour Damage with Critical Hits is Lucky\nEnemies' Damage with Critical Hits against you is Lucky"
			}
		},
		stats={
			[1]="keystone_sharp_and_brittle"
		}
	},
	[202]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Ignore [Attributes|Attribute] Requirements\nGain no inherent bonuses from [Attributes]",
				text="Ignore Attribute Requirements\nGain no inherent bonuses from Attributes"
			}
		},
		stats={
			[1]="keystone_supreme_prodigy"
		}
	},
	[203]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="Regenerate 1 Life per second per 16 Life spent in the past 4 seconds\n20% more Life Cost of Skills",
				text="Regenerate 1 Life per second per 16 Life spent in the past 4 seconds\n20% more Life Cost of Skills"
			}
		},
		stats={
			[1]="keystone_tecrods_brutality"
		}
	},
	[204]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="50% of Cold and Lightning Damage taken as Fire Damage\n50% less Cold Resistance\n50% less Lightning Resistance",
				text="50% of Cold and Lightning Damage taken as Fire Damage\n50% less Cold Resistance\n50% less Lightning Resistance"
			}
		},
		stats={
			[1]="keystone_tempered_by_war"
		}
	},
	[205]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Projectile|Projectiles] do one of the following at random:\n• [Fork] an additional time\n• [Chain] an additional time\n• [Chain] from Terrain an additional time\n• Cannot collide with targets",
				text="Projectiles do one of the following at random:\nFork an additional time\nChain an additional time\nChain from Terrain an additional time\nCannot collide with targets"
			}
		},
		stats={
			[1]="keystone_ulamans_vision"
		}
	},
	[206]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="-25% to maximum Chance to Block [Attack] Damage\n-25% to maximum Chance to Block Spell Damage\n+2% Chance to Block Spell Damage for each 1% Overcapped Chance to Block [Attack] Damage",
				text="-25% to maximum Chance to Block Attack Damage\n-25% to maximum Chance to Block Spell Damage\n+2% Chance to Block Spell Damage for each 1% Overcapped Chance to Block Attack Damage"
			}
		},
		stats={
			[1]="keystone_versatile_combatant"
		}
	},
	[207]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="+10% to all Elemental Resistances and maximum Elemental Resistances while affected by a Non-Vaal Guard Skill\n20% additional Physical Damage Reduction while affected by a Non-Vaal Guard Skill\n20% more Damage taken if a Non-Vaal Guard Buff was lost [Recently]",
				text="+10% to all Elemental Resistances and maximum Elemental Resistances while affected by a Non-Vaal Guard Skill\n20% additional Physical Damage Reduction while affected by a Non-Vaal Guard Skill\n20% more Damage taken if a Non-Vaal Guard Buff was lost Recently"
			}
		},
		stats={
			[1]="keystone_veterans_awareness"
		}
	},
	[208]={
		[1]={
			[1]={
				limit={
					[1]={
						[1]="#",
						[2]="#"
					}
				},
				rawText="[Storm|Storm] and [Plant|Plant] [Spell|Spells]:\n• deal 50% more damage\n• cost 50% less\n• have 75% less duration",
				text="Storm and Plant Spells:\ndeal 50% more damage\ncost 50% less\nhave 75% less duration"
			}
		},
		stats={
			[1]="keystone_wildsurge_incantation"
		}
	},
	["active_skill_additional_projectiles_description_mode"]=44,
	["adaptation_duration_ms"]=51,
	["add_frenzy_charge_on_kill"]=17,
	["additional_combo_gain_chance_%"]=53,
	["aggravate_bleeding_when_inflicted_vs_pinned_enemy"]=54,
	["arcane_surge_effect_on_self_+%_per_10%_missing_mana"]=55,
	["ascendancy_arcane_archer_triggered_skill_mana_cost_+%_final"]=56,
	["ascendancy_chronomancer_apex_of_the_moment_base_slow_aura_value"]=57,
	["ascendancy_disconnected_passives_can_be_allocated_around_allocated_keystones"]=58,
	["ascendancy_druid_shaman_elemental_damage_taken_+%_final_per_matching_adaptation"]=104,
	["ascendancy_gemling_charge_generator_buff_display"]=59,
	["ascendancy_gemling_enable_thaumaturgy_quality_stats"]=60,
	["ascendancy_lich_consume_power_for_apparition"]=61,
	["ascendancy_lich_skeletons_are_buffs_instead_of_minions"]=62,
	["ascendancy_lich_spell_damage_+%_final_when_sacrificing_energy_shield"]=152,
	["ascendancy_lich_spells_consume_power_charges_for_spell_damage_+%_final"]=63,
	["ascendancy_non_unique_jewel_radius_+%"]=135,
	["ascendancy_oracle_can_allocate_additional_oracle_only_passives_display"]=64,
	["ascendancy_random_ignite_effect_+%_final_up_to_%"]=65,
	["ascendancy_ritualist_damage_+%_final_vs_enemies_affected_by_blood_boil"]=66,
	["ascendancy_shaman_+_spirit_per_empty_charm_slot"]=67,
	["ascendancy_shaman_spell_damage_+%_final_per_2_rage"]=68,
	["ascendancy_spell_deja_vu_skill_echo_chance_%"]=69,
	["ascendancy_spell_deja_vu_spell_%_chance_to_reoccur_an_additional_time"]=70,
	["ascendancy_tactician_suppressing_fire_hit_damage_immobilisation_multiplier_+%_final"]=71,
	["ascendancy_whispers_of_the_flesh_cursed_enemies_have_at_least_life_reserved_%"]=72,
	["base_devotion"]=2,
	["base_dexterity"]=7,
	["base_dexterity_and_intelligence"]=42,
	["base_intelligence"]=9,
	["base_number_of_golems_allowed"]=45,
	["base_number_of_raging_spirits_allowed"]=24,
	["base_number_of_skeletons_allowed"]=23,
	["base_number_of_spectres_allowed"]=22,
	["base_phasing_without_visual"]=158,
	["base_rage_regeneration_rate_per_minute_%"]=73,
	["base_strength"]=5,
	["base_strength_and_dexterity"]=40,
	["base_strength_and_intelligence"]=41,
	["base_tribute"]=3,
	["blood_mage_life_flask_buff_%_charges_to_consume"]=74,
	["blood_mage_life_flask_buff_%_damage_to_gain_as_physical_per_charge_consumed"]=74,
	["blood_mage_life_flask_buff_duration_ms"]=74,
	["can_equip_staff_with_focus"]=75,
	["can_gain_combo_from_any_attack_hit"]=76,
	["can_only_spawn_blue_flame_of_chayula_remnants"]=77,
	["can_only_spawn_purple_flame_of_chayula_remnants"]=78,
	["can_only_spawn_red_flame_of_chayula_remnants"]=79,
	["chance_%_for_extra_infusion_on_infused_remnant_pickup"]=81,
	["chance_for_extra_damage_roll_%"]=80,
	["chance_to_generate_owl_feather_%_on_crit"]=82,
	["charge_skip_consume_chance_%"]=83,
	["chill_effect_+%"]=84,
	["chronomancer_damage_taken_+%_final"]=85,
	["chronomancer_grant_area_of_effect_+%"]=86,
	["chronomancer_grant_cast_speed_+%"]=86,
	["chronomancer_take_%_of_hit_damage_4_seconds_after_being_hit"]=87,
	["consecrate_ground_on_kill_%_for_3_seconds"]=47,
	["created_remnants_have_%_chance_to_duplicate_pick_up_results"]=88,
	["critical_chance_vs_self_is_unlucky"]=89,
	["critical_strike_chance_+%"]=34,
	["crushing_blow"]=90,
	["current_energy_shield_%_as_elemental_damage_reduction"]=91,
	["damage_taken_+%_from_hits"]=1,
	["damage_taken_from_hits_is_unlucky"]=92,
	["daze_enemies_on_block_with_shield_raised_chance_%"]=93,
	["dexterity_+%"]=8,
	["display_can_take_character_start_point"]=46,
	["display_fire_djinn_enable_living_bomb"]=94,
	["display_nearby_enemies_are_taunted"]=95,
	["display_sand_djinn_enable_explode_teleport"]=96,
	["display_sand_djinn_enable_hand_slam"]=97,
	["display_sand_djinn_enable_knife_throw"]=98,
	["display_travellers_wisdom_extra_attribute_options"]=99,
	["display_you_have_x_fortification"]=100,
	["djinn_ascendancy_energy_shield_recharge_rate_+%_final_on_low_energy_shield"]=101,
	["double_adaptation_effect"]=102,
	["elemental_archon_does_not_expire_while_on_high_infernal_flame"]=112,
	["elemental_damage_removed_from_mana_before_life_%"]=103,
	["elemental_skill_limit_+"]=105,
	["energy_shield_recharge_starts_X_ms_sooner"]=48,
	["every_1_second_nearby_enemies_withered_for_X_ms"]=106,
	["focus_mod_effect_+%"]=107,
	["gain_X_adaptation_matching_type_when_hit_by_elemental_damage"]=52,
	["gain_X_life_flask_charges_per_4%_life_spent"]=49,
	["gain_X_volatility_on_inflicting_elemental_ailment"]=108,
	["gain_elemental_archon_when_you_cast_a_spell_while_on_high_infernal_flame"]=111,
	["global_armour_evasion_energy_shield_+%"]=50,
	["global_chance_to_blind_on_hit_%"]=43,
	["hit_damage_remove_from_mana_before_life_while_mana_higher_than_life"]=109,
	["immune_to_volatility_damage"]=110,
	["intelligence_+%"]=10,
	["keystone_2_companions"]=114,
	["keystone_acrobatics"]=25,
	["keystone_alternate_dexterity_bonus"]=161,
	["keystone_alternate_es_recovery"]=162,
	["keystone_alternate_intelligence_bonus"]=163,
	["keystone_alternate_strength_bonus"]=164,
	["keystone_amanamus_defiance"]=165,
	["keystone_ancestral_bond"]=21,
	["keystone_auto_invocation"]=166,
	["keystone_avatar_of_fire"]=19,
	["keystone_barbed_tips"]=167,
	["keystone_blind_monk"]=168,
	["keystone_blood_magic"]=29,
	["keystone_bulwark"]=115,
	["keystone_call_to_arms"]=169,
	["keystone_chaos_inoculation"]=32,
	["keystone_charge_cycle"]=170,
	["keystone_conduit"]=28,
	["keystone_crimson_assault"]=116,
	["keystone_crimson_dance"]=117,
	["keystone_dance_with_death"]=118,
	["keystone_disciple_of_kitava"]=171,
	["keystone_divine_flesh"]=172,
	["keystone_divine_shield"]=173,
	["keystone_druidic_rage"]=174,
	["keystone_eldritch_battery"]=20,
	["keystone_elemental_equilibrium"]=31,
	["keystone_elemental_overload"]=175,
	["keystone_emperors_heart"]=176,
	["keystone_eternal_youth"]=177,
	["keystone_fire_spells_become_chaos_spells"]=178,
	["keystone_focused_rage"]=179,
	["keystone_giants_blood"]=119,
	["keystone_glancing_blows"]=180,
	["keystone_heartstopper"]=181,
	["keystone_herald_of_doom"]=182,
	["keystone_hex_master"]=183,
	["keystone_hollow_palm_technique"]=184,
	["keystone_impale"]=185,
	["keystone_iron_grip"]=186,
	["keystone_iron_reflexes"]=18,
	["keystone_iron_will"]=187,
	["keystone_kulemaks_sovereignty"]=188,
	["keystone_kurgals_ambition"]=189,
	["keystone_lord_of_the_wilds"]=190,
	["keystone_magnetic_charge"]=191,
	["keystone_mana_shield"]=36,
	["keystone_mental_conditioning"]=192,
	["keystone_minion_instability"]=30,
	["keystone_natures_presence"]=193,
	["keystone_oasis"]=194,
	["keystone_pain_attunement"]=26,
	["keystone_point_blank"]=27,
	["keystone_precise_technique"]=195,
	["keystone_prismatic_bulwark"]=196,
	["keystone_quiet_might"]=197,
	["keystone_runebinder"]=198,
	["keystone_sacred_bastion"]=199,
	["keystone_secrets_of_suffering"]=200,
	["keystone_sharp_and_brittle"]=201,
	["keystone_supreme_prodigy"]=202,
	["keystone_tecrods_brutality"]=203,
	["keystone_tempered_by_war"]=204,
	["keystone_ulamans_vision"]=205,
	["keystone_unwavering_stance"]=38,
	["keystone_vaal_pact"]=33,
	["keystone_versatile_combatant"]=206,
	["keystone_veterans_awareness"]=207,
	["keystone_wildsurge_incantation"]=208,
	["keystone_zealots_oath"]=120,
	["leech_also_recovers_based_on_chaos_damage_as_well"]=121,
	["lich_offering_effect_+%_per_enemy_power"]=159,
	["life_leech_is_instant_for_empowered_attacks"]=122,
	["life_mastery_nearby_enemy_life_regeneration_rate_+%"]=123,
	["local_jewel_display_number_of_allocated_passives_between_jewel_and_class_start"]=160,
	["lose_elemental_archone_on_reaching_full_infernal_flame"]=113,
	["mana_regeneration_rate_modifiers_apply_to_rage_regeneration"]=124,
	["mana_regeneration_rate_per_minute_%"]=11,
	["mana_regeneration_rate_per_minute_%_per_power_charge"]=12,
	["max_endurance_charges"]=13,
	["max_frenzy_charges"]=14,
	["max_power_charges"]=15,
	["maximum_block_chance_override"]=125,
	["maximum_darkness_+%_per_capped_chaos_damage_resistance"]=126,
	["maximum_mana_per_50_evasion_rating_from_armour_items"]=127,
	["minion_non_skill_base_elemental_damage_%_to_gain_as_chaos"]=128,
	["movement_speed_penalty_+%_final_while_performing_action_if_green_support_count_highest"]=134,
	["movement_speed_penalty_+%_while_raising_shield"]=129,
	["multishot_critical_damage_bonus_+%_final"]=130,
	["natures_sustenance_added_rage_cost"]=131,
	["natures_sustenance_additional_maximum_rage"]=132,
	["no_barrage_projectile_spread"]=133,
	["no_self_critical_strike_multiplier_if_red_support_count_highest"]=134,
	["number_of_additional_projectiles"]=44,
	["offering_skill_target_cullable_enemies_instead"]=136,
	["offerings_only_buff_you"]=137,
	["oracle_hits_eventually_crit_with_critical_strike_multiplier_+%_final_per_failed_roll"]=138,
	["oracle_maximum_life_+%_final"]=139,
	["oracle_maximum_mana_+%_final"]=140,
	parent="stat_descriptions",
	["passive_can_be_allocated_without_connection"]=39,
	["physical_damage_+%"]=141,
	["physical_damage_+%_per_frenzy_charge"]=16,
	["physical_spell_damage_can_pin_on_critical_hit"]=142,
	["pinned_enemies_cannot_crit"]=143,
	["pinned_enemies_cannot_evade_your_attacks"]=144,
	["projectile_attacks_always_chain_to_marked_enemies_with_%_increased_chaining_distance"]=145,
	["rage_gained_on_life_flask_use"]=146,
	["random_freeze_duration_+%_up_to_%"]=147,
	["remnants_you_create_reappear_X_ms_after_being_collected"]=148,
	["resolute_technique"]=37,
	["sacrificing_energy_shield_does_not_interrupt_recharge"]=149,
	["shock_effect_+%"]=150,
	["skill_cost_+%_final_if_blue_support_count_highest"]=134,
	["skill_cost_+%_per_socketed_soul_core"]=151,
	["spells_sacrifice_%_of_your_energy_shield"]=152,
	["staff_block_%"]=35,
	["start_at_zero_energy_shield"]=153,
	["strength_+%"]=6,
	["tactician_grants_aura_to_deployed_totems"]=154,
	["tribute_+%"]=4,
	["unlimited_banners_allowed"]=155,
	["unravelling_cycling_buff_every_x_ms"]=156,
	["weapon_damage_%_granted_to_companions"]=157
}